import { Injectable } from '@angular/core';

@Injectable()
export class UnitsInfoService {
  private conversionDescriptions: any = {
    "celsius": `<section id="celsius-unit" aria-label="Celsius Temperature Unit Description">        <h3>Celsius Temperature Unit</h3>        <p>The Celsius temperature unit (celsius), also called the degree Celsius (°C), is a broadly used unit for            measuring temperature inside the metric system. It is based totally on the Celsius scale, in which zero°C is the freezing            point of water, and a hundred°C is the boiling point of water beneath general atmospheric stress.</p>        <p>Conversion to Celsius: <strong>1 Celsius (celsius) = 1 Celsius (celsius)</strong></p>        <p>The Celsius scale is usually used in everyday lifestyles for weather forecasts, cooking, and clinical            programs. In the conversion feature, the cost stays unchanged, as it's already in Celsius.</p>    </section>`,
    "fahrenheit": `<section id="fahrenheit-unit" aria-label="Fahrenheit Temperature Unit Description">        <h3>Fahrenheit Temperature Unit</h3>        <p>The Fahrenheit temperature unit (fahrenheit), additionally known as the degree Fahrenheit (°F), is a temperature            scale generally used in the United States and some other international locations. In the Fahrenheit scale, 32°F is the            freezing factor of water, and 212°F is the boiling point of water underneath trendy atmospheric pressure.</p>        <p>Conversion to Celsius: <strong>Celsius (°C) = (Fahrenheit (°F) - 32) × 5/nine</strong></p>        <p>Fahrenheit is normally used within the United States for weather reporting, cooking, and a few engineering            programs. The conversion characteristic subtracts 32 from the Fahrenheit price, then multiplies by way of five/nine to            attain the equal Celsius temperature.</p>    </section>`,
    "kelvin": `<section id="kelvin-unit" aria-label="Kelvin Temperature Unit Description">        <h3>Kelvin Temperature Unit</h3>        <p>The Kelvin temperature unit (kelvin), symbolized as K, is the bottom unit of temperature in the International            System of Units (SI). It is an absolute temperature scale wherein zero K, referred to as absolute zero, represents the            lowest possible temperature, at which all molecular motion ceases.</p>        <p>Conversion to Celsius: <strong>Celsius (°C) = Kelvin (K) - 273.15</strong></p>        <p>Kelvin is generally utilized in scientific and engineering packages, particularly in fields including physics,            chemistry, and thermodynamics. The conversion characteristic subtracts 273.15 from the Kelvin fee to attain the            equal Celsius temperature.</p>    </section>`,
    "rankine": `<section id="rankine-unit" aria-label="Rankine Temperature Unit Description">        <h3>Rankine Temperature Unit</h3>        <p>The Rankine temperature unit (rankine), symbolized as R, is an absolute temperature scale this is broadly speaking            utilized in engineering packages, particularly within the United States. It is just like the Kelvin scale however            makes use of a special 0 factor. Absolute 0 at the Rankine scale is zero R.</p>        <p>Conversion to Celsius: <strong>Celsius (°C) = (Rankine (°R) - 491.67) × five/9</strong></p>        <p>Rankine is regularly used in thermodynamics, engineering, and some aerospace programs, particularly inside the            United States. The conversion characteristic first subtracts 491.67 from the Rankine cost and then multiplies by way of            5/nine to reap the equal Celsius temperature.</p>    </section>`,
    "reaumur": `<section id="reaumur-unit" aria-label="Réaumur Temperature Unit Description">        <h3>Réaumur Temperature Unit</h3>        <p>The Réaumur temperature unit (reaumur), symbolized as °Re or °Ré, is a historical temperature scale that was            as soon as usually utilized in Europe. It divides the temperature range between the freezing and boiling points of            water into 80 same parts, with zero°Ré as the freezing factor and eighty°Ré as the boiling factor of water beneath            standard atmospheric strain.</p>        <p>Conversion to Celsius: <strong>Celsius (°C) = Réaumur (°Ré) × 5/4</strong></p>        <p>While the Réaumur scale is no longer in big use, it has historical importance within the development of            temperature dimension. The conversion feature multiplies the Réaumur cost by means of 5/4 to acquire the            equivalent Celsius temperature.</p>    </section>`,
    "romer": `<section id="romer-unit" aria-label="Romer Temperature Unit Description">        <h3>Romer Temperature Unit</h3>        <p>The Romer temperature unit (romer), symbolized as °Rø, is a historical temperature scale advanced by means of Danish            astronomer Ole Rømer in the 18th century. The Romer scale divides the temperature range among the freezing            and boiling factors of water into 60 identical components, with zero°Rø because the freezing factor and 60°Rø because the boiling            factor of water beneath trendy atmospheric strain.</p>        <p>Conversion to Celsius: <strong>Celsius (°C) = (Romer (°Rø) - 7.5) × 40/21</strong></p>        <p>The Romer scale is no longer in commonplace use but has historic importance in the records of temperature            size. The conversion feature subtracts 7.5 from the Romer value, then multiplies by way of forty/21 to acquire            the equivalent Celsius temperature.</p>    </section>`,
    "delisle": `<section id="delisle-unit" aria-label="Delisle Temperature Unit Description">        <h3>Delisle Temperature Unit</h3>        <p>The Delisle temperature unit (delisle), additionally called the degree Delisle (°De), is a historical temperature            scale advanced through French astronomer Joseph-Nicolas Delisle within the 18th century. In the Delisle scale, zero°De            is the boiling point of water, and a hundred and fifty°De is the freezing factor of water below trendy atmospheric            pressure.</p>        <p>Conversion to Celsius: <strong>Celsius (°C) = one hundred - (Delisle (°De) × 2/3)</strong></p>        <p>Like other historic scales, the Delisle scale is no longer widely used. The conversion characteristic calculates            the equal Celsius temperature by using subtracting the Delisle fee from one hundred and then multiplying by 2/3.        </p>    </section>`,
    "newton": `<section id="newton-unit" aria-label="Newton Temperature Unit Description">        <h3>Newton Temperature Unit</h3>        <p>The Newton temperature unit (newton), symbolized as °N, is a temperature scale advanced via English scientist            Isaac Newton. It divides the temperature range among the freezing and boiling factors of water into 33            same components, with zero°N as the freezing point and 33°N as the boiling factor of water beneath preferred            atmospheric strain.</p>        <p>Conversion to Celsius: <strong>Celsius (°C) = (Newton (°N) × a hundred/33)</strong></p>        <p>The Newton scale is much less common than the Celsius and Fahrenheit scales. The conversion feature calculates            the equivalent Celsius temperature with the aid of multiplying the Newton price via a hundred/33.</p>    </section>`,
    "centigrade": `<section id="centigrade-unit" aria-label="Centigrade Temperature Unit Description">        <h3>Centigrade Temperature Unit</h3>        <p>The Centigrade temperature unit (centigrade), also referred to as the diploma Centigrade (°C), is an opportunity            call for the Celsius scale. It is a widely used unit for measuring temperature in the metric machine, in which            0°C is the freezing point of water, and 100°C is the boiling factor of water below popular atmospheric            pressure.</p>        <p>Conversion to Celsius: <strong>Celsius (°C) = Centigrade (°C)</strong></p>        <p>The Centigrade scale is largely equal to the Celsius scale, and the conversion feature reflects this            by means of leaving the value unchanged.</p>    </section>`,
    "gas-mark": `<section id="gas-mark-unit" aria-label="Gas Mark Temperature Unit Description">        <h3>Gas Mark Temperature Unit</h3>        <p>The Gas Mark temperature unit (gas_mark) is a temperature scale used in cooking, specifically inside the United            Kingdom and a few other international locations. It is by and large used to indicate oven temperatures for baking and            roasting. Gas Mark values commonly variety from 1 to nine or higher.</p>        <p>Conversion to Celsius: <strong>Celsius (°C) = (Gas Mark - 1) × 25 + a hundred and fifty</strong></p>        <p>The Gas Mark scale enables chefs set the proper oven temperature for diverse recipes. The conversion characteristic            subtracts 1 from the Gas Mark cost, multiplies with the aid of 25, and then provides one hundred fifty to reap the equivalent Celsius            temperature.</p>    </section>`,
    "planck-temperature": `<section id="planck-temperature-unit" aria-label="Planck Temperature Unit Description">        <h3>Planck Temperature Unit</h3>        <p>The Planck Temperature unit (planck) is a essential unit of temperature in the context of Planck devices, a            set of herbal gadgets used in theoretical physics. It is described in relation to different fundamental constants            of the universe, mainly Planck's regular, the velocity of light, and the Boltzmann regular.</p>        <p>Conversion to Celsius: <strong>Celsius (°C) = Planck Temperature (planck) × 1.41680833e+32</strong></p>        <p>The Planck Temperature is a really high temperature and is utilized in theoretical physics, mainly in            the look at of quantum gravity and cosmology. The conversion feature multiplies the Planck Temperature price            by using 1.41680833e+32 to achieve the equal Celsius temperature.</p>    </section>`
   }

  getDescription(unitName: string) {
    return this.conversionDescriptions[unitName];
  }


}