import { Injectable } from '@angular/core';

@Injectable()
export class UnitsInfoService {
  private conversionDescriptions: any = {
    "meter-per-second": `<section id="meter-per-second" aria-label="Meter per Second Speed Unit Description">    <h3>Meter per Second</h3>    <p>Meter per second (m/s) is a trendy unit of pace in the International System of Units (SI). It represents the gap of 1 meter traveled in a single second. This unit is widely utilized in scientific and engineering applications to degree velocity and pace.</p>    <p>Conversion: <strong>1 Meter per Second (m/s) = 0.277778 Kilometers per Hour (km/h) = zero.44704 Miles per Hour (mph) = three.28084 Feet per Second (feet/s) = 1.94384 Knots (kn)</strong></p>    <p>Meter per second is normally used in physics, fluid dynamics, and sports to calculate the price of motion and exchange in position.</p></section>`,
    "kilometer-per-hour": `<section id="kilometer-per-hour" aria-label="Kilometer per Hour Speed Unit Description">    <h3>Kilometer per Hour</h3>    <p>Kilometer per hour (km/h) is a metric unit of pace that represents the gap of one kilometer traveled in one hour. It's a general unit for measuring vehicle pace in most nations that use the metric machine.</p>    <p>Conversion: <strong>1 Kilometer per Hour (km/h) = 3.6 Kilometers per Second (m/s) = zero.621371 Miles per Hour (mph) = three.28084 Feet per Second (ft/s) = 1.94384 Knots (kn)</strong></p>    <p>Kilometers per hour is commonly used for pace limits, vehicle speedometers, and determining the pace of tour.</p></section>`,
    "mile-per-hour": `<section id="mile-per-hour" aria-label="Mile per Hour Speed Unit Description">    <h3>Mile per Hour</h3>    <p>Mile per hour (mph) is an imperial unit of velocity that represents the distance of 1 mile traveled in one hour. It's broadly used inside the United States and some other countries that comply with the imperial gadget for measuring automobile pace.</p>    <p>Conversion: <strong>1 Mile per Hour (mph) = 1.60934 Kilometers per Hour (km/h) = zero.277778 Meters per Second (m/s) = 1.46667 Feet per Second (toes/s) = 0.868976 Knots (kn)</strong></p>    <p>Miles per hour is the same old unit for street pace limits and is frequently visible on vehicle speedometers in nations that use the imperial gadget.</p></section>`,
    "foot-per second": `<section id="foot-per-second" aria-label="Foot per Second Speed Unit Description">    <h3>Foot per Second</h3>    <p>Foot per second (feet/s) is an imperial unit of speed that represents the distance of 1 foot traveled in a single second. It's typically used in various engineering and physics packages within the United States and different nations following the imperial device.</p>    <p>Conversion: <strong>1 Foot per Second (feet/s) = 0.3048 Meters per Second (m/s) = 1.09728 Kilometers per Hour (km/h) = 0.681818 Miles per Hour (mph) = 0.592484 Knots (kn)</strong></p>    <p>Foot per second is regularly utilized in fluid dynamics, acoustics, and mechanics to degree pace and speed.</p></section>`,
    "knot": `<section id="knot" aria-label="Knot Speed Unit Description">    <h3>Knot</h3>    <p>A knot (kn) is a unit of velocity often used in maritime and aviation contexts. It represents one nautical mile per hour, that is a widespread for measuring the velocity of ships and plane visiting over water or via the air.</p>    <p>Conversion: <strong>1 Knot (kn) = 1.852 Kilometers per Hour (km/h) = 0.514444 Meters per Second (m/s) = 1.15078 Miles per Hour (mph) = 1.68781 Feet per Second (feet/s)</strong></p>    <p>Knots are essential for navigation, climate forecasting, and flight planning inside the transportation enterprise.</p></section>`,
    "mach": `<section id="mach" aria-label="Mach Speed Unit Description">    <h3>Mach</h3>    <p>Mach (Ma) is a unit of speed that represents an object's velocity relative to the rate of sound inside the surrounding medium. It's commonly used in aviation and aerospace to denote the ratio of an plane's pace to the velocity of sound.</p>    <p>Conversion: <strong>1 Mach (Ma) = 343.058 Meters per Second (m/s) = 1235.07 Kilometers per Hour (km/h) = 767.269 Miles per Hour (mph) = 1125.33 Feet per Second (ft/s)</strong></p>    <p>Mach numbers are important for assessing the performance and conduct of plane at high speeds.</p></section>`,
    "light-per-second": `<section id="light-per-second" aria-label="Speed of Light (c) Speed Unit Description">    <h3>Speed of Light (c)</h3>    <p>The velocity of light (c) is an absolute regular in physics, representing the maximum velocity at which information or count number can journey in a vacuum. It plays a fundamental role inside the idea of relativity and various medical programs.</p>    <p>Conversion: <strong>1 Speed of Light (c) = 299,792,458 Meters per Second (m/s) = 1,079,252,848.8 Kilometers per Hour (km/h) = 670,616,629.4 Miles per Hour (mph) = 983,571,056.Four Feet per Second (toes/s)</strong></p>    <p>The pace of mild is a fundamental constant in physics and is crucial for knowledge the behavior of electromagnetic waves and the principles of relativity.</p></section>`,
    "kilometer-per-second": `<section id="kilometer-per-second" aria-label="Kilometer per Second Speed Unit Description">    <h3>Kilometer per Second</h3>    <p>Kilometer per second (km/s) is a metric unit of pace that represents the gap of 1 kilometer traveled in one second. It's regularly utilized in medical and engineering contexts for unique speed measurements.</p>    <p>Conversion: <strong>1 Kilometer per Second (km/s) = 1,000 Meters per Second (m/s) = 3,six hundred Kilometers per Hour (km/h) = 2,236.94 Miles per Hour (mph) = three,280.84 Feet per Second (toes/s)</strong></p>    <p>Kilometers per second is a convenient unit for describing excessive-pace phenomena in physics and engineering.</p></section>`,
    "centimeter-per-second": `<section id="centimeter-per-second" aria-label="Centimeter per Second Speed Unit Description">    <h3>Centimeter per Second</h3>    <p>Centimeter per second (cm/s) is a metric unit of pace that represents the distance of 1 centimeter traveled in a single second. It's regularly used for specific measurements of gradual or small-scale motion in scientific and engineering packages.</p>    <p>Conversion: <strong>1 Centimeter per Second (cm/s) = 0.01 Meters per Second (m/s) = 0.036 Kilometers per Hour (km/h) = zero.0224 Miles per Hour (mph) = zero.0328 Feet per Second (feet/s)</strong></p>    <p>Centimeters per second is ideal for measuring minute changes in function and speed.</p></section>`,
    "millimeter-per-second": `<section id="millimeter-per-second" aria-label="Millimeter per Second Speed Unit Description">    <h3>Millimeter per Second</h3>    <p>Millimeter per second (mm/s) is a metric unit of pace that represents the gap of 1 millimeter traveled in a single second. It's used for extremely specific measurements of sluggish or small-scale movement in medical and engineering contexts.</p>    <p>Conversion: <strong>1 Millimeter per Second (mm/s) = 0.001 Meters per Second (m/s) = zero.0036 Kilometers per Hour (km/h) = 0.0022 Miles per Hour (mph) = zero.0.33 Feet per Second (feet/s)</strong></p>    <p>Millimeters per second is the desired unit for measuring ultra-unique actions and changes in position.</p></section>`,
    "yard-per-second": `<section id="yard-per-second" aria-label="Yard per Second Speed Unit Description">    <h3>Yard per Second</h3>    <p>Yard per second (yd/s) is a unit of velocity that represents the space of 1 yard traveled in one second. It's utilized in diverse applications, together with sports and engineering, where yards are a commonplace unit of size.</p>    <p>Conversion: <strong>1 Yard per Second (yd/s) = zero.9144 Meters per Second (m/s) = 1.09728 Kilometers per Hour (km/h) = zero.681818 Miles per Hour (mph) = 3 Feet per Second (ft/s)</strong></p>    <p>Yards per second are often used in sports activities together with American football to explain the velocity of gamers or gadgets on the sector.</p></section>`,
    "mile-per-second": `<section id="mile-per-second" aria-label="Mile per Second Speed Unit Description">    <h3>Mile per Second</h3>    <p>Mile per second (mi/s) is a unit of speed that represents the gap of one mile traveled in one second. It's used for describing high-speed motion in various clinical and engineering contexts.</p>    <p>Conversion: <strong>1 Mile per Second (mi/s) = 1609.34 Meters per Second (m/s) = 5793.64 Kilometers per Hour (km/h) = 3600 Miles per Hour (mph) = 5280 Feet per Second (feet/s)</strong></p>    <p>Miles per second is a unit that reveals software in conditions concerning extraordinarily fast movement, such as in particle physics or astrophysics.</p></section>`,
    "inch-per-second": `<section id="inch-per-second" aria-label="Inch per Second Speed Unit Description">    <h3>Inch per Second</h3>    <p>Inch per second (in/s) is a unit of speed that represents the gap of 1 inch traveled in one second. It's often used for specific measurements of small-scale movement in engineering and manufacturing.</p>    <p>Conversion: <strong>1 Inch per Second (in/s) = 0.0254 Meters per Second (m/s) = 0.09144 Kilometers per Hour (km/h) = 0.05682 Miles per Hour (mph) = zero.08333 Feet per Second (feet/s)</strong></p>    <p>Inches per second is right for quantifying the rate of moving mechanical additives in machinery.</p></section>`,
    "microinch-per-second": `<section id="microinch-per-second" aria-label="Microinch per Second Speed Unit Description">    <h3>Microinch per Second</h3>    <p>Microinch per second (µin/s) is a really small unit of speed that represents the gap of 1 microinch traveled in a single second. It's used for ultra-precise measurements of minuscule movements in clinical and engineering applications.</p>    <p>Conversion: <strong>1 Microinch per Second (µin/s) = 2.54e-08 Meters per Second (m/s) = 9.144e-08 Kilometers per Hour (km/h) = 5.682e-08 Miles per Hour (mph) = eight.333e-08 Feet per Second (toes/s)</strong></p>    <p>Microinches per second is essential for measuring microscopic movements and vibrations in specialized system and studies.</p></section>`,
    "millimeter-per-hour": `<section id="millimeter-per-hour" aria-label="Millimeter per Hour Speed Unit Description">    <h3>Millimeter per Hour</h3>    <p>Millimeter per hour (mm/h) is a unit of speed that represents the gap of one millimeter traveled in a single hour. It's used for measuring very sluggish or gradual adjustments in role over prolonged intervals.</p>    <p>Conversion: <strong>1 Millimeter per Hour (mm/h) = 2.77778e-07 Meters per Second (m/s) = 0.001 Kilometers per Hour (km/h) = 0.000621371 Miles per Hour (mph) = 0.00091144 Feet per Second (toes/s)</strong></p>    <p>Millimeters per hour is appropriate for quantifying the fee of slow strategies, which include sedimentation or fabric deposition.</p></section>`,
    "centimeter-per-hour": `<section id="centimeter-per-hour" aria-label="Centimeter per Hour Speed Unit Description">    <h3>Centimeter per Hour</h3>    <p>Centimeter per hour (cm/h) is a unit of speed that represents the space of 1 centimeter traveled in a single hour. It's used for measuring very slow and gradual modifications or motion over prolonged durations of time.</p>    <p>Conversion: <strong>1 Centimeter per Hour (cm/h) = 2.77778e-06 Meters per Second (m/s) = zero.00001 Kilometers per Hour (km/h) = 0.0000062137 Miles per Hour (mph) = zero.0000091144 Feet per Second (ft/s)</strong></p>    <p>Centimeters per hour is a useful unit for quantifying sluggish techniques along with sedimentation, or for measuring extraordinarily slow actions.</p></section>`,
    "kilometer-per-millisecond": `<section id="kilometer-per-millisecond" aria-label="Kilometer per Millisecond Speed Unit Description">    <h3>Kilometer per Millisecond</h3>    <p>Kilometer per millisecond (km/ms) is a unit of pace that represents the space of one kilometer traveled in one millisecond. It's used for describing extraordinarily excessive-speed motion in scientific and technical contexts, consisting of in physics experiments or superior engineering.</p>    <p>Conversion: <strong>1 Kilometer per Millisecond (km/ms) = a million Meters per Second (m/s) = 3600000 Kilometers per Hour (km/h) = 2236936.4 Miles per Hour (mph) = 3280840.Eighty four Feet per Second (feet/s)</strong></p>    <p>Kilometers per millisecond is an essential unit for measuring speedy activities and high-pace phenomena with precision.</p></section>`,
    "meter-per-millisecond": `<section id="meter-per-millisecond" aria-label="Meter per Millisecond Speed Unit Description">    <h3>Meter per Millisecond</h3>    <p>Meter per millisecond (m/ms) is a unit of speed that represents the distance of one meter traveled in one millisecond. It's regularly utilized in clinical and engineering packages to quantify fast motion or alternate over short time intervals.</p>    <p>Conversion: <strong>1 Meter per Millisecond (m/ms) = 1000 Meters per Second (m/s) = 3600000 Kilometers per Hour (km/h) = 2236936.Four Miles per Hour (mph) = 3280840.84 Feet per Second (toes/s)</strong></p>    <p>Meters per millisecond is a precious unit for precise measurements of speedy-transferring gadgets or activities.</p></section>`,
    "foot-per-millisecond": `<section id="foot-per-millisecond" aria-label="Foot per Millisecond Speed Unit Description">    <h3>Foot per Millisecond</h3>    <p>Foot per millisecond (feet/ms) is a unit of pace that represents the space of one foot traveled in a single millisecond. It's utilized in scientific and technical packages to quantify speedy movement or trade on a totally small timescale.</p>    <p>Conversion: <strong>1 Foot per Millisecond (toes/ms) = 0.3048 Meters per Second (m/s) = 1.09728 Kilometers per Hour (km/h) = zero.681818 Miles per Hour (mph) = 3 Feet per Second (ft/s)</strong></p>    <p>Feet per millisecond is essential for measuring brief moves, particularly in regions like robotics or high-pace checking out.</p></section>`,
    "inch-per-millisecond": `<section id="inch-per-millisecond" aria-label="Inch per Millisecond Speed Unit Description">    <h3>Inch per Millisecond</h3>    <p>Inch per millisecond (in/ms) is a unit of velocity that represents the space of one inch traveled in one millisecond. It's employed in particular measurements of small-scale rapid moves in clinical and engineering programs.</p>    <p>Conversion: <strong>1 Inch per Millisecond (in/ms) = zero.0254 Meters per Second (m/s) = 0.09144 Kilometers per Hour (km/h) = zero.05682 Miles per Hour (mph) = 0.08333 Feet per Second (toes/s)</strong></p>    <p>Inches per millisecond is a precious unit for quantifying extraordinarily speedy and precise motion, along with in nanotechnology or advanced robotics.</p></section>`
  }

  getDescription(unitName: string) {
    return this.conversionDescriptions[unitName];
  }


}