import { Injectable } from '@angular/core';

@Injectable()
export class UnitsInfoService {
  private conversionDescriptions: any = {
  "bit": `<section id="bit" aria-label="Bit Description"><h3>Bit [b]</h3><p>The bit (b) is the smallest unit of statistics in computing and digital conversation. It can constitute certainly one of two values, typically zero or 1, and is the fundamental building block of virtual data. Bits are crucial for encoding and processing information in computers and digital devices.</p><p>Conversion: <strong>1 Bit (b) = 0.125 Byte (B)</strong></p><p>Bits play a significant position in computer technological know-how, statistics theory, and facts transmission, serving as the muse for encoding and transmitting information.</p></section>`,
  "nibble": `<section id="nibble" aria-label="Nibble Description">          <h3>Nibble</h3>          <p>A nibble is a group of 4 bits (b). It serves as a convenient 1/2-byte unit for records garage and               manipulation. Nibbles are utilized in diverse computing packages, along with low-level programming and               statistics processing, where managing smaller units of information is wonderful.</p>          <p>Conversion: <strong>1 Nibble = 4 Bits (b)</strong></p>          <p>Nibbles are mainly beneficial in contexts where facts needs to be divided into smaller, possible chunks               for processing or garage.</p>     </section>`,
  "byte": `<section id="byte" aria-label="Byte [B] Description">          <h3>Byte [B]</h3>          <p>A byte (B) consists of 8 bits (b) and is a fundamental unit of digital statistics storage and               processing. Bytes are the constructing blocks of statistics in computing and are used to represent characters,               numbers, and different information in diverse encoding schemes.</p>          <p>Conversion: <strong>1 Byte (B) = 8 Bits (b)</strong></p>          <p>Bytes are on the center of computer reminiscence, report storage, and facts communication protocols, making them a               important component of current computing systems.</p>     </section>`,
  "character": `<section id="character" aria-label="Character Description">          <h3>Character</h3>          <p>A person is generally encoded the use of eight bits (one byte) and represents a single alphanumeric or               unique image. Characters are the inspiration of human-readable text in virtual shape and are vital               for textual content processing, encoding, and display in software applications.</p>          <p>Conversion: <strong>1 Character = eight Bits (1 Byte)</strong></p>          <p>Characters are the basis for writing and displaying textual content in numerous languages and are quintessential to word               processing, programming, and conversation.</p>     </section>`,
  "word": `<section id="word" aria-label="Word Description">          <h3>Word</h3>          <p>A word is a grouping of 16 bits, that is equal to two bytes. The size of a word varies in               distinct computing architectures, however it's miles commonly used to represent a unit of statistics that a processor               can technique in a unmarried operation. Word length plays a crucial function in laptop architecture and               performance.</p>          <p>Conversion: <strong>1 Word = 16 Bits (2 Bytes)</strong></p>          <p>Word length is a essential element in figuring out a laptop's processing abilties and reminiscence addressing,               influencing the performance and performance of software program and hardware structures.</p>     </section>`,
  "MAPM-word": `<section id="MAPM-word" aria-label="MAPM-Word Description">          <h3>MAPM-Word</h3>          <p>A MAPM-Word is a unit of records containing 32 bits. It's utilized in computing and digital structures for numerous               packages, including facts processing, memory control, and mathematical calculations. The MAPM-Word               length lets in for representing a huge range of values and appearing complex operations effectively.</p>          <p>Conversion: <strong>1 MAPM-Word = 32 Bits</strong></p>          <p>MAPM-Words are a not unusual statistics size in lots of computer architectures and play a critical role in each               widespread-purpose and specialised computing responsibilities.</p>     </section>`,
  "quadruple-word": `<section id="quadruple-word" aria-label="Quadruple Word Description">          <h3>Quadruple Word</h3>          <p>A Quadruple Word consists of sixty four bits, which is 4 instances the size of a general word. This unit is used in               computing for applications requiring large information garage and processing talents. Quadruple Words are               frequent in structures coping with great statistics sets and high-performance computing.</p>          <p>Conversion: <strong>1 Quadruple Word = 64 Bits (2 MAPM-Words)</strong></p>          <p>Quadruple Words provide a considerable growth in facts dealing with capability and are vital in medical,               engineering, and information-intensive computing environments.</p>     </section>`,
  "block": `<section id="block" aria-label="Block Description">          <h3>Block</h3>          <p>A block is a unit of information garage usually which includes 512 bits or 64 bytes. Blocks are essential in               report structures, disk garage, and facts control. They are used for organizing and coping with information on               garage gadgets correctly.</p>          <p>Conversion: <strong>1 Block = 512 Bits (8 Quadruple Words)</strong></p>          <p>Blocks are crucial to disk I/O operations, information retrieval, and garage allocation in pc systems,               making sure green and prepared information access.</p>     </section>`,
  "kilobit": `<section id="kilobit" aria-label="Kilobit [kb] Description">          <h3>Kilobit [kb]</h3>          <p>A kilobit (kb) is a unit of facts identical to one,000 bits. It's normally used in data conversation, networking,               and net-related contexts to measure facts transfer costs and storage capacities. Kilobits are               vital for expressing statistics speeds and sizes in the digital international.</p>          <p>Conversion: <strong>1 Kilobit (kb) = 1,000 Bits</strong></p>          <p>Kilobits are frequently used to explain internet connection speeds, report down load/upload fees, and information               transmission costs in telecommunications.</p>     </section>`,
  "kilobyte": `<section id="kilobyte" aria-label="Kilobyte [kB] Description">          <h3>Kilobyte [kB]</h3>          <p>A kilobyte (kB) is a unit of data garage identical to 8,000 bits or 1,000 bytes. Kilobytes are typically used               for measuring record sizes, memory capacities, and facts storage in laptop structures. They offer a               practical and effortlessly workable unit for records garage and retrieval.</p>          <p>Conversion: <strong>1 Kilobyte (kB) = 8,000 Bits (eight Kilobits)</strong></p>          <p>Kilobytes are widely employed in report sizes, memory specifications, and information garage capacity discussions               in computing and facts technology.</p>     </section>`,
  "kilobyte-10": `<section id="kilobyte-10" aria-label="Kilobyte (10^3 bytes) Description">          <h3>Kilobyte (10^3 bytes)</h3>          <p>A Kilobyte (KB), with a base of 10^3 bytes (1,000 bytes), is a unit of statistics storage utilized in computing and               virtual systems. It represents a convenient length for measuring record sizes, reminiscence capacities, and information               storage in realistic applications.</p>          <p>Conversion: <strong>1 Kilobyte (KB, 10^3 bytes) = 8,000 Bits (eight Kilobits)</strong></p>          <p>Kilobytes with a base of 10^3 bytes are typically hired to describe record sizes, memory specifications,               and facts storage ability in computing and statistics generation.</p>     </section>`,
  "megabit": `<section id="megabit" aria-label="Megabit [Mb] Description">          <h3>Megabit [Mb]</h3>          <p>A Megabit (Mb) is a unit of facts equal to a million bits. It's normally utilized in facts communication,               networking, and telecommunications to degree information switch charges and community speeds. Megabits are               crucial for expressing high-speed information transmission.</p>          <p>Conversion: <strong>1 Megabit (Mb) = one million Bits (1,000 Kilobits)</strong></p>          <p>Megabits are often used to specify net connection speeds, information switch quotes, and community               bandwidth in telecommunications and virtual conversation.</p>     </section>`,
  "megabyte": `<section id="megabyte" aria-label="Megabyte [MB] Description">          <h3>Megabyte [MB]</h3>          <p>A Megabyte (MB) is a unit of facts garage identical to eight,000,000 bits or one million bytes. Megabytes are extensively               used for measuring report sizes, reminiscence capacities, and facts storage in computing systems. They provide a               practical unit for statistics garage and retrieval.</p>          <p>Conversion: <strong>1 Megabyte (MB) = 8,000,000 Bits (8 Megabits)</strong></p>          <p>Megabytes are necessary in discussions about file sizes, memory specs, and records storage capability in               the field of computing and statistics generation.</p>     </section>`,
  "megabyte-10": `<section id="megabyte-10" aria-label="Megabyte (10^6 bytes) Description">          <h3>Megabyte (10^6 bytes)</h3>          <p>A Megabyte (MB) with a base of 10^6 bytes (one million bytes) is a unit of facts storage utilized in computing and               virtual structures. It represents a convenient length for measuring record sizes, reminiscence capacities, and facts               storage in practical packages.</p>          <p>Conversion: <strong>1 Megabyte (MB, 10^6 bytes) = 8,000,000 Bits (eight Megabits)</strong></p>          <p>Megabytes with a base of 10^6 bytes are usually hired to explain file sizes, memory specs,               and data garage capability in computing and information era.</p>     </section>`,
  "gigabit": `<section id="gigabit" aria-label="Gigabit [Gb] Description">          <h3>Gigabit [Gb]</h3>          <p>A Gigabit (Gb) is a unit of data identical to a million,000 bits. It's ordinarily utilized in statistics communique,               networking, and telecommunications to measure high-velocity records switch charges and community capacities.               Gigabits are critical for expressing ultra-speedy statistics transmission.</p>          <p>Conversion: <strong>1 Gigabit (Gb) = 1,000,000,000 Bits (1,000 Megabits)</strong></p>          <p>Gigabits are frequently used to specify net connection speeds, network bandwidth, and facts transfer               quotes in advanced telecommunications and digital verbal exchange.</p>     </section>`,
  "gigabyte": `<section id="gigabyte" aria-label="Gigabyte [GB] Description">          <h3>Gigabyte [GB]</h3>          <p>A Gigabyte (GB) is a unit of statistics storage identical to 8,000,000,000 bits or a million,000 bytes. Gigabytes are               generally used for measuring big facts garage capacities in computing and digital systems. They offer               a realistic unit for records garage and retrieval.</p>          <p>Conversion: <strong>1 Gigabyte (GB) = eight,000,000,000 Bits (8 Gigabits)</strong></p>          <p>Gigabytes are vital in discussions about document sizes, memory specs, and data garage potential in               the field of computing and statistics era.</p>     </section>`,
  "gigabyte-10": `<section id="gigabyte-10" aria-label="Gigabyte (10^9 bytes) Description">          <h3>Gigabyte (10^9 bytes)</h3>          <p>A Gigabyte (GB) with a base of 10^9 bytes (1,000,000,000 bytes) is a unit of records garage used in computing               and digital systems. It represents a handy length for measuring large records garage capacities in               practical packages.</p>          <p>Conversion: <strong>1 Gigabyte (GB, 10^9 bytes) = eight,000,000,000 Bits (eight Gigabits)</strong></p>          <p>Gigabytes with a base of 10^9 bytes are usually employed to describe report sizes, reminiscence specs,               and statistics storage capacity in computing and information era.</p>     </section>`,
  "terabit": `<section id="terabit" aria-label="Terabit [Tb] Description">          <h3>Terabit [Tb]</h3>          <p>A Terabit (Tb) is a unit of information same to a million,000,000 bits. It's more often than not used in facts               conversation, networking, and telecommunications to degree extremely high-speed information transfer quotes and               community capacities. Terabits are important for expressing extremely-speedy records transmission.</p>          <p>Conversion: <strong>1 Terabit (Tb) = 1,000,000,000,000 Bits (1,000 Gigabits)</strong></p>          <p>Terabits are frequently used to specify net spine speeds, statistics center network ability, and               advanced telecommunications systems.</p>     </section>`,
  "terabyte": `<section id="terabyte" aria-label="Terabyte [TB] Description">          <h3>Terabyte [TB]</h3>          <p>A Terabyte (TB) is a unit of records storage equal to 8,000,000,000,000 bits or a million,000 bytes. Terabytes               are broadly used for measuring large records storage capacities in computing systems. They provide a               practical unit for information storage and retrieval, specifically for big datasets.</p>          <p>Conversion: <strong>1 Terabyte (TB) = 8,000,000,000,000 Bits (eight Terabits)</strong></p>          <p>Terabytes play a critical function in discussions approximately records storage, backup solutions, and handling massive               amounts of digital facts within the area of computing and statistics technology.</p>     </section>`,
  "terabyte-10": `<section id="terabyte-10" aria-label="Terabyte (10^12 bytes) Description">          <h3>Terabyte (10^12 bytes)</h3>          <p>A Terabyte (TB) with a base of 10^12 bytes (one million,000,000 bytes) is a unit of facts storage utilized in               computing and virtual systems. It represents an even larger size for measuring very massive records               garage capacities in practical applications.</p>          <p>Conversion: <strong>1 Terabyte (TB, 10^12 bytes) = 8,000,000,000,000 Bits (8 Terabits)</strong></p>          <p>Terabytes with a base of 10^12 bytes are normally hired to describe storage answers for substantial               datasets, data centers, and company-stage information control in computing and statistics technology.</p>     </section>`,
  "petabit": `<section id="petabit" aria-label="Petabit [Pb] Description">          <h3>Petabit [Pb]</h3>          <p>A Petabit (Pb) is a unit of records same to a million,000,000,000 bits or 1,000 Terabits. It's primarily used               in excessive-ability information transmission and storage systems to explicit tremendously large facts volumes.               Petabits are critical for measuring statistics transfer charges and capacities at an unprecedented scale.</p>          <p>Conversion: <strong>1 Petabit [Pb] = a million,000,000,000 Bits [b]</strong></p>          <p>Petabits are crucial in discussions approximately supercomputing, worldwide statistics networks, and superior statistics-intensive               packages that contain big records coping with.</p>     </section>`,
  "petabyte": `<section id="petabyte" aria-label="Petabyte [PB] Description">          <h3>Petabyte [PB]</h3>          <p>A Petabyte (PB) is a unit of information garage equal to 8,000,000,000,000,000 bits or 1,000 Terabytes. Petabytes               are extensively used for measuring massive information garage capacities, mainly in big-scale facts centers,               cloud computing, and large records programs. They constitute an giant scale for information storage and               control.</p>          <p>Conversion: <strong>1 Petabyte [PB] = 8,000,000,000,000,000 Bits [b]</strong></p>          <p>Petabytes play a important position in discussions approximately data storage infrastructure, archival structures, and               dealing with big amounts of facts inside the virtual age.</p>     </section>`
  }


  getDescription(unitName: string) {
    return this.conversionDescriptions[unitName];
  }


}