import { Injectable } from '@angular/core';

@Injectable()
export class UnitsInfoService {
  private conversionDescriptions: any = {
  "meter-per-liter": `<section id="meter-per-liter" aria-label="Meter per Liter Fuel Efficiency Unit Description">        <h3>Meter per Liter</h3>                <p>Meter per liter (m/L) is a unit of gasoline efficiency that represents the space traveled in meters on one liter of gas. It is a widespread metric unit utilized in many countries to degree the fuel performance of vehicles.</p>             <p>Conversion: <strong>1 Meter per Liter (m/L) = 1 Meter per Liter (m/L)</strong></p>             <p>Meters per liter is a not unusual unit for measuring fuel performance in countries the usage of the metric gadget.</p>    </section>`,
  "kilometer-per-liter": `<section id="kilometer-per-liter" aria-label="Kilometer per Liter Fuel Efficiency Unit Description">        <h3>Kilometer per Liter</h3>                <p>Kilometer per liter (km/L) is a unit of gasoline performance that represents the gap traveled in kilometers on one liter of gas. It is extensively used for measuring gas efficiency in nations the use of the metric system.</p>             <p>Conversion: <strong>1 Kilometer per Liter (km/L) = zero.001 Meter per Liter (m/L)</strong></p>             <p>Kilometers per liter provide a bigger scale for expressing gas performance, usually used in Europe and other metric countries.</p>    </section>`,
  "mile-per-gallon-us": `<section id="mile-per-gallon-us" aria-label="Mile per Gallon (US) Fuel Efficiency Unit Description">        <h3>Mile per Gallon (US)</h3>                <p>Mile per gallon (US) is a unit of fuel efficiency used primarily in the United States. It represents the space traveled in miles on one gallon (U.S.) of gas. This unit is usually used for measuring fuel efficiency inside the U.S.</p>             <p>Conversion: <strong>1 Mile per Gallon (US) = zero.000160358 Meter per Liter (m/L)</strong></p>             <p>Miles per gallon (US) offer a handy way to explicit gasoline efficiency for American purchasers.</p>    </section>`,
  "mile-per-gallon-uk": `<section id="mile-per-gallon-uk" aria-label="Mile per Gallon (UK) Fuel Efficiency Unit Description">        <h3>Mile per Gallon (UK)</h3>                <p>Mile per gallon (UK) is a unit of gas efficiency used inside the United Kingdom and some other nations. It represents the gap traveled in miles on one gallon (UK) of fuel.</p>             <p>Conversion: <strong>1 Mile per Gallon (UK) = zero.000117845 Meter per Liter (m/L)</strong></p>             <p>Miles per gallon (UK) offer a extraordinary measurement for gasoline efficiency compared to the U.S. Gallon, and it is utilized in regions following the imperial system.</p>    </section>`,
  "liter-per-100-kilometers": `<section id="liter-per-100-kilometers" aria-label="Liter per 100 Kilometers Fuel Efficiency Unit Description">        <h3>Liter per 100 Kilometers</h3>                <p>Liter per one hundred kilometers (L/100km) is a unit of fuel performance used in a few European international locations and different areas. It represents the volume of gasoline fed on in liters per one hundred kilometers traveled.</p>             <p>Conversion: <strong>1 Liter per a hundred Kilometers (L/100km) = zero.01 Meter per Liter (m/L)</strong></p>             <p>Liters per a hundred kilometers provide a direct degree of gas intake in metric nations, permitting consumers to recognize gasoline efficiency effortlessly.</p>    </section>`,
  "kilometer-per-gallon-us": `<section id="kilometer-per-gallon-us" aria-label="Kilometer per Gallon (US) Fuel Efficiency Unit Description">        <h3>Kilometer per Gallon (US)</h3>                <p>Kilometer per gallon (US) is a unit of gasoline efficiency used mostly in the United States. It represents the distance traveled in kilometers on one gallon (U.S.) of gas. This unit is commonly used for measuring gasoline efficiency inside the U.S.</p>             <p>Conversion: <strong>1 Kilometer per Gallon (US) = 0.000160934 Meter per Liter (m/L)</strong></p>             <p>Kilometers per gallon (US) provide a convenient way to express gas performance for American customers.</p>    </section>`,
  "kilometer-per-gallon-uk": `<section id="kilometer-per-gallon-uk" aria-label="Kilometer per Gallon (UK) Fuel Efficiency Unit Description">        <h3>Kilometer per Gallon (UK)</h3>                <p>Kilometer per gallon (UK) is a unit of fuel efficiency used in the United Kingdom and some other countries. It represents the space traveled in kilometers on one gallon (UK) of gasoline.</p>             <p>Conversion: <strong>1 Kilometer per Gallon (UK) = 0.000134481 Meter per Liter (m/L)</strong></p>             <p>Kilometers per gallon (UK) offer a exceptional size for gas performance in comparison to the U.S. Gallon, and it is used in regions following the imperial system.</p>    </section>`,
  "meter-per-gallon-us": `<section id="meter-per-gallon-us" aria-label="Meter per Gallon (US) Fuel Efficiency Unit Description">        <h3>Meter per Gallon (US)</h3>                <p>Meter per gallon (US) is a unit of fuel efficiency that represents the distance traveled in meters on one gallon (U.S.) of gasoline. It is a wellknown metric unit utilized in many countries to degree the gas performance of vehicles.</p>             <p>Conversion: <strong>1 Meter per Gallon (US) = 1.61e-7 Meter per Liter (m/L)</strong></p>             <p>Meters per gallon (US) provide a unique metric size for gas performance.</p>    </section>`,
  "meter-per-gallon-uk": `<section id="meter-per-gallon-uk" aria-label="Meter per Gallon (UK) Fuel Efficiency Unit Description">        <h3>Meter per Gallon (UK)</h3>                <p>Meter per gallon (UK) is a unit of fuel performance used within the United Kingdom and a few different nations. It represents the space traveled in meters on one gallon (UK) of fuel.</p>             <p>Conversion: <strong>1 Meter per Gallon (UK) = 1.34e-7 Meter per Liter (m/L)</strong></p>             <p>Meters per gallon (UK) provide a one of a kind metric dimension for gasoline efficiency in comparison to the U.S. Gallon.</p>    </section>`,
  "nautical-mile-per-liter": `<section id="nautical-mile-per-liter" aria-label="Nautical Mile per Liter Fuel Efficiency Unit Description">        <h3>Nautical Mile per Liter</h3>                <p>Nautical mile per liter is a unit of gas efficiency that represents the distance traveled in nautical miles on one liter of gasoline.</p>             <p>Conversion: <strong>1 Nautical Mile per Liter = zero.000539956 Meter per Liter (m/L)</strong></p>             <p>Nautical miles per liter is a unit utilized in maritime and navigation contexts.</p>    </section>`,
  "nautical-mile-per-gallon-us": `<section id="nautical-mile-per-gallon-us" aria-label="Nautical Mile per Gallon (US) Fuel Efficiency Unit Description">        <h3>Nautical Mile per Gallon (US)</h3>                <p>Nautical mile per gallon (US) is a unit of fuel performance utilized in maritime and navigation contexts. It represents the gap traveled in nautical miles on one gallon (U.S.) of fuel.</p>             <p>Conversion: <strong>1 Nautical Mile per Gallon (US) = 9.16e-7 Meter per Liter (m/L)</strong></p>             <p>Nautical miles per gallon (US) is a specialized unit for measuring gas efficiency in marine applications.</p>    </section>`,
  "nautical-mile-per-gallon-uk": `<section id="nautical-mile-per-gallon-uk" aria-label="Nautical Mile per Gallon (UK) Fuel Efficiency Unit Description">        <h3>Nautical Mile per Gallon (UK)</h3>                <p>Nautical mile per gallon (UK) is any other unit of gasoline efficiency utilized in maritime and navigation contexts, mostly within the United Kingdom and comparable regions. It represents the gap traveled in nautical miles on one gallon (UK) of fuel.</p>             <p>Conversion: <strong>1 Nautical Mile per Gallon (UK) = 7.62e-7 Meter per Liter (m/L)</strong></p>             <p>Nautical miles per gallon (UK) gives a one of a kind size for fuel efficiency in comparison to the U.S. Gallon and is used in regions following the imperial gadget.</p>    </section>`,
  "kilometer-per-cubic-meter": `<section id="kilometer-per-cubic-meter" aria-label="Kilometer per Cubic Meter Fuel Efficiency Unit Description">        <h3>Kilometer per Cubic Meter</h3>                <p>Kilometer per cubic meter is a unit of gasoline performance that measures the gap traveled in kilometers on one cubic meter of gas. It's typically used for unique packages requiring gas performance measurements at a volume degree.</p>             <p>Conversion: <strong>1 Kilometer per Cubic Meter = 0.001 Meter per Liter (m/L)</strong></p>             <p>Kilometers per cubic meter is used while managing fuel performance at a volumetric scale.</p>    </section>`,
  "mile-per-cubic-yard": `<section id="mile-per-cubic-yard" aria-label="Mile per Cubic Yard Fuel Efficiency Unit Description">        <h3>Mile per Cubic Yard</h3>                <p>Mile per cubic yard is a unique unit of gas efficiency representing the gap traveled in miles on one cubic yard of gas. This unit isn't always typically used however gives an opportunity size for gasoline performance.</p>             <p>Conversion: <strong>1 Mile per Cubic Yard = 1.30795 Meter per Liter (m/L)</strong></p>             <p>Miles per cubic yard is an unusual unit for fuel performance calculations.</p>    </section>`,
  "meter-per-cubic-foot": `<section id="meter-per-cubic-foot" aria-label="Meter per Cubic Foot Fuel Efficiency Unit Description">        <h3>Meter per Cubic Foot</h3>                <p>Meter per cubic foot is a unit of fuel efficiency that measures the gap traveled in meters on one cubic foot of gas. It offers a metric size for gasoline efficiency at a volumetric scale.</p>             <p>Conversion: <strong>1 Meter per Cubic Foot = 0.0283168 Meter per Liter (m/L)</strong></p>             <p>Meters per cubic foot is a metric unit for gas performance calculations.</p>    </section>`,
  "mile-per-liter": `<section id="mile-per-liter" aria-label="Mile per Liter Fuel Efficiency Unit Description">    <h3>Mile per Liter</h3>        <p>Mile per liter is a unit of gas efficiency that represents the space traveled in miles on one liter of fuel. It's generally used in international locations that measure gas efficiency in miles and liters.</p>     <p>Conversion: <strong>1 Mile per Liter (mi/L) = zero.000621371 Meter per Liter (m/L)</strong></p>     <p>Miles per liter is a trendy unit for fuel efficiency, in particular in regions in which the metric device isn't always normally used for this reason.</p></section>`,
  "kilometer-per-cubic-foot": `<section id="kilometer-per-cubic-foot" aria-label="Kilometer per Cubic Foot Fuel Efficiency Unit Description">    <h3>Kilometer per Cubic Foot</h3>        <p>Kilometer per cubic foot is a unit of fuel efficiency that measures the gap traveled in kilometers on one cubic foot of gasoline. It affords a metric size for gasoline performance at a volumetric scale.</p>     <p>Conversion: <strong>1 Kilometer per Cubic Foot (km/ft³) = 0.0283168 Meter per Liter (m/L)</strong></p>     <p>Kilometers per cubic foot is a metric unit for gasoline efficiency calculations, more often than not for volumetric gas measurements.</p></section>`,
  "mile-per-cubic-meter": `<section id="mile-per-cubic-meter" aria-label="Mile per Cubic Meter Fuel Efficiency Unit Description">    <h3>Mile per Cubic Meter</h3>        <p>Mile per cubic meter is a unit of gas performance representing the distance traveled in miles on one cubic meter of gas. It's used for measuring gas performance at a volumetric stage within the metric system.</p>     <p>Conversion: <strong>1 Mile per Cubic Meter (mi/m³) = 6.21e-7 Meter per Liter (m/L)</strong></p>     <p>Miles per cubic meter is a metric unit for gasoline performance calculations, that specialize in gas quantity inside the metric gadget.</p></section>`,
  "mile-per-cubic-inch": `<section id="mile-per-cubic-inch" aria-label="Mile per Cubic Inch Fuel Efficiency Unit Description">    <h3>Mile per Cubic Inch</h3>        <p>Mile per cubic inch is a unit of gasoline efficiency that represents the space traveled in miles on one cubic inch of gas. It's a specialised unit used for particular measurements of gasoline efficiency at very small volumes.</p>     <p>Conversion: <strong>1 Mile per Cubic Inch (mi/in³) = 2.54e-8 Meter per Liter (m/L)</strong></p>     <p>Miles per cubic inch is a tiny unit for fuel efficiency calculations, ordinarily in specialized fields.</p></section>`,
  "meter-per-cubic-inch": `<section id="meter-per-cubic-inch" aria-label="Meter per Cubic Inch Fuel Efficiency Unit Description">    <h3>Meter per Cubic Inch</h3>        <p>Meter per cubic inch is a unit of gas performance that measures the gap traveled in meters on one cubic inch of gas. It's used for particular measurements of gas performance at small volumes in the metric machine.</p>     <p>Conversion: <strong>1 Meter per Cubic Inch (m/in³) = zero.0000610236 Meter per Liter (m/L)</strong></p>     <p>Meters per cubic inch is a metric unit for gas performance calculations, in particular in technical packages requiring small extent measurements.</p></section>`,
  "mile-per-cubic-centimeter": `<section id="mile-per-cubic-centimeter" aria-label="Mile per Cubic Centimeter Fuel Efficiency Unit Description">    <h3>Mile per Cubic Centimeter</h3>        <p>Mile per cubic centimeter is a unit of gasoline performance that represents the gap traveled in miles on one cubic centimeter of gas. It's a very specialized unit used for extraordinarily unique measurements of gasoline performance at minuscule volumes.</p>     <p>Conversion: <strong>1 Mile per Cubic Centimeter (mi/cm³) = 6.21e-7 Meter per Liter (m/L)</strong></p>     <p>Miles per cubic centimeter is an extremely small unit for fuel performance calculations, typically employed in exceedingly specialized programs requiring ultra-precise quantity measurements.</p></section>`
  }

  getDescription(unitName: string) {
    return this.conversionDescriptions[unitName];
  }


}