import { Injectable } from '@angular/core';

@Injectable()
export class UnitsInfoService {
  private conversionDescriptions: any = {
    "meter-per-liter": "<section id=\"meter-per-liter\" aria-label=\"Meter per Liter Fuel Efficiency Unit Description\">\n        <h3>Meter per Liter</h3>\n        \n        <p>Meter per liter (m/L) is a unit of fuel efficiency that represents the distance traveled in meters on one liter of fuel. It is a standard metric unit used in many countries to measure the fuel efficiency of vehicles.</p>\n     \n        <p>Conversion: <strong>1 Meter per Liter (m/L) = 1 Meter per Liter (m/L)</strong></p>\n     \n        <p>Meters per liter is a common unit for measuring fuel efficiency in countries using the metric system.</p>\n    </section>",
    "kilometer-per-liter": "<section id=\"kilometer-per-liter\" aria-label=\"Kilometer per Liter Fuel Efficiency Unit Description\">\n        <h3>Kilometer per Liter</h3>\n        \n        <p>Kilometer per liter (km/L) is a unit of fuel efficiency that represents the distance traveled in kilometers on one liter of fuel. It is widely used for measuring fuel efficiency in countries using the metric system.</p>\n     \n        <p>Conversion: <strong>1 Kilometer per Liter (km/L) = 0.001 Meter per Liter (m/L)</strong></p>\n     \n        <p>Kilometers per liter provide a larger scale for expressing fuel efficiency, commonly used in Europe and other metric countries.</p>\n    </section>",
    "mile-per-gallon-us": "<section id=\"mile-per-gallon-us\" aria-label=\"Mile per Gallon (US) Fuel Efficiency Unit Description\">\n        <h3>Mile per Gallon (US)</h3>\n        \n        <p>Mile per gallon (US) is a unit of fuel efficiency used primarily in the United States. It represents the distance traveled in miles on one gallon (U.S.) of fuel. This unit is commonly used for measuring fuel efficiency in the U.S.</p>\n     \n        <p>Conversion: <strong>1 Mile per Gallon (US) = 0.000160358 Meter per Liter (m/L)</strong></p>\n     \n        <p>Miles per gallon (US) provide a convenient way to express fuel efficiency for American consumers.</p>\n    </section>",
    "mile-per-gallon-uk": "<section id=\"mile-per-gallon-uk\" aria-label=\"Mile per Gallon (UK) Fuel Efficiency Unit Description\">\n        <h3>Mile per Gallon (UK)</h3>\n        \n        <p>Mile per gallon (UK) is a unit of fuel efficiency used in the United Kingdom and some other countries. It represents the distance traveled in miles on one gallon (UK) of fuel.</p>\n     \n        <p>Conversion: <strong>1 Mile per Gallon (UK) = 0.000117845 Meter per Liter (m/L)</strong></p>\n     \n        <p>Miles per gallon (UK) provide a different measurement for fuel efficiency compared to the U.S. gallon, and it's used in regions following the imperial system.</p>\n    </section>",
    "liter-per-100-kilometers": "<section id=\"liter-per-100-kilometers\" aria-label=\"Liter per 100 Kilometers Fuel Efficiency Unit Description\">\n        <h3>Liter per 100 Kilometers</h3>\n        \n        <p>Liter per 100 kilometers (L/100km) is a unit of fuel efficiency used in some European countries and other regions. It represents the volume of fuel consumed in liters per 100 kilometers traveled.</p>\n     \n        <p>Conversion: <strong>1 Liter per 100 Kilometers (L/100km) = 0.01 Meter per Liter (m/L)</strong></p>\n     \n        <p>Liters per 100 kilometers provide a direct measure of fuel consumption in metric countries, allowing consumers to understand fuel efficiency easily.</p>\n    </section>",
    "kilometer-per-gallon-us": "<section id=\"kilometer-per-gallon-us\" aria-label=\"Kilometer per Gallon (US) Fuel Efficiency Unit Description\">\n        <h3>Kilometer per Gallon (US)</h3>\n        \n        <p>Kilometer per gallon (US) is a unit of fuel efficiency used primarily in the United States. It represents the distance traveled in kilometers on one gallon (U.S.) of fuel. This unit is commonly used for measuring fuel efficiency in the U.S.</p>\n     \n        <p>Conversion: <strong>1 Kilometer per Gallon (US) = 0.000160934 Meter per Liter (m/L)</strong></p>\n     \n        <p>Kilometers per gallon (US) provide a convenient way to express fuel efficiency for American consumers.</p>\n    </section>",
    "kilometer-per-gallon-uk": "<section id=\"kilometer-per-gallon-uk\" aria-label=\"Kilometer per Gallon (UK) Fuel Efficiency Unit Description\">\n        <h3>Kilometer per Gallon (UK)</h3>\n        \n        <p>Kilometer per gallon (UK) is a unit of fuel efficiency used in the United Kingdom and some other countries. It represents the distance traveled in kilometers on one gallon (UK) of fuel.</p>\n     \n        <p>Conversion: <strong>1 Kilometer per Gallon (UK) = 0.000134481 Meter per Liter (m/L)</strong></p>\n     \n        <p>Kilometers per gallon (UK) provide a different measurement for fuel efficiency compared to the U.S. gallon, and it's used in regions following the imperial system.</p>\n    </section>",
    "meter-per-gallon-us": "<section id=\"meter-per-gallon-us\" aria-label=\"Meter per Gallon (US) Fuel Efficiency Unit Description\">\n        <h3>Meter per Gallon (US)</h3>\n        \n        <p>Meter per gallon (US) is a unit of fuel efficiency that represents the distance traveled in meters on one gallon (U.S.) of fuel. It is a standard metric unit used in many countries to measure the fuel efficiency of vehicles.</p>\n     \n        <p>Conversion: <strong>1 Meter per Gallon (US) = 1.61e-7 Meter per Liter (m/L)</strong></p>\n     \n        <p>Meters per gallon (US) provide a precise metric measurement for fuel efficiency.</p>\n    </section>",
    "meter-per-gallon-uk": "<section id=\"meter-per-gallon-uk\" aria-label=\"Meter per Gallon (UK) Fuel Efficiency Unit Description\">\n        <h3>Meter per Gallon (UK)</h3>\n        \n        <p>Meter per gallon (UK) is a unit of fuel efficiency used in the United Kingdom and some other countries. It represents the distance traveled in meters on one gallon (UK) of fuel.</p>\n     \n        <p>Conversion: <strong>1 Meter per Gallon (UK) = 1.34e-7 Meter per Liter (m/L)</strong></p>\n     \n        <p>Meters per gallon (UK) provide a different metric measurement for fuel efficiency compared to the U.S. gallon.</p>\n    </section>",
    "nautical-mile-per-liter": "<section id=\"nautical-mile-per-liter\" aria-label=\"Nautical Mile per Liter Fuel Efficiency Unit Description\">\n        <h3>Nautical Mile per Liter</h3>\n        \n        <p>Nautical mile per liter is a unit of fuel efficiency that represents the distance traveled in nautical miles on one liter of fuel.</p>\n     \n        <p>Conversion: <strong>1 Nautical Mile per Liter = 0.000539956 Meter per Liter (m/L)</strong></p>\n     \n        <p>Nautical miles per liter is a unit used in maritime and navigation contexts.</p>\n    </section>",
    "nautical-mile-per-gallon-us": "<section id=\"nautical-mile-per-gallon-us\" aria-label=\"Nautical Mile per Gallon (US) Fuel Efficiency Unit Description\">\n        <h3>Nautical Mile per Gallon (US)</h3>\n        \n        <p>Nautical mile per gallon (US) is a unit of fuel efficiency used in maritime and navigation contexts. It represents the distance traveled in nautical miles on one gallon (U.S.) of fuel.</p>\n     \n        <p>Conversion: <strong>1 Nautical Mile per Gallon (US) = 9.16e-7 Meter per Liter (m/L)</strong></p>\n     \n        <p>Nautical miles per gallon (US) is a specialized unit for measuring fuel efficiency in marine applications.</p>\n    </section>",
    "nautical-mile-per-gallon-uk": "<section id=\"nautical-mile-per-gallon-uk\" aria-label=\"Nautical Mile per Gallon (UK) Fuel Efficiency Unit Description\">\n        <h3>Nautical Mile per Gallon (UK)</h3>\n        \n        <p>Nautical mile per gallon (UK) is another unit of fuel efficiency used in maritime and navigation contexts, primarily in the United Kingdom and similar regions. It represents the distance traveled in nautical miles on one gallon (UK) of fuel.</p>\n     \n        <p>Conversion: <strong>1 Nautical Mile per Gallon (UK) = 7.62e-7 Meter per Liter (m/L)</strong></p>\n     \n        <p>Nautical miles per gallon (UK) provides a different measurement for fuel efficiency compared to the U.S. gallon and is used in regions following the imperial system.</p>\n    </section>",
    "kilometer-per-cubic-meter": "<section id=\"kilometer-per-cubic-meter\" aria-label=\"Kilometer per Cubic Meter Fuel Efficiency Unit Description\">\n        <h3>Kilometer per Cubic Meter</h3>\n        \n        <p>Kilometer per cubic meter is a unit of fuel efficiency that measures the distance traveled in kilometers on one cubic meter of fuel. It's commonly used for specific applications requiring fuel efficiency measurements at a volume level.</p>\n     \n        <p>Conversion: <strong>1 Kilometer per Cubic Meter = 0.001 Meter per Liter (m/L)</strong></p>\n     \n        <p>Kilometers per cubic meter is used when dealing with fuel efficiency at a volumetric scale.</p>\n    </section>",
    "mile-per-cubic-yard": "<section id=\"mile-per-cubic-yard\" aria-label=\"Mile per Cubic Yard Fuel Efficiency Unit Description\">\n        <h3>Mile per Cubic Yard</h3>\n        \n        <p>Mile per cubic yard is a unique unit of fuel efficiency representing the distance traveled in miles on one cubic yard of fuel. This unit is not commonly used but provides an alternative measurement for fuel efficiency.</p>\n     \n        <p>Conversion: <strong>1 Mile per Cubic Yard = 1.30795 Meter per Liter (m/L)</strong></p>\n     \n        <p>Miles per cubic yard is an uncommon unit for fuel efficiency calculations.</p>\n    </section>",
    "meter-per-cubic-foot": "<section id=\"meter-per-cubic-foot\" aria-label=\"Meter per Cubic Foot Fuel Efficiency Unit Description\">\n        <h3>Meter per Cubic Foot</h3>\n        \n        <p>Meter per cubic foot is a unit of fuel efficiency that measures the distance traveled in meters on one cubic foot of fuel. It provides a metric measurement for fuel efficiency at a volumetric scale.</p>\n     \n        <p>Conversion: <strong>1 Meter per Cubic Foot = 0.0283168 Meter per Liter (m/L)</strong></p>\n     \n        <p>Meters per cubic foot is a metric unit for fuel efficiency calculations.</p>\n    </section>",
    "mile-per-liter": "<section id=\"mile-per-liter\" aria-label=\"Mile per Liter Fuel Efficiency Unit Description\">\n    <h3>Mile per Liter</h3>\n    \n    <p>Mile per liter is a unit of fuel efficiency that represents the distance traveled in miles on one liter of fuel. It's commonly used in countries that measure fuel efficiency in miles and liters.</p>\n \n    <p>Conversion: <strong>1 Mile per Liter (mi/L) = 0.000621371 Meter per Liter (m/L)</strong></p>\n \n    <p>Miles per liter is a standard unit for fuel efficiency, especially in regions where the metric system is not commonly used for this purpose.</p>\n</section>",
    "kilometer-per-cubic-foot": "<section id=\"kilometer-per-cubic-foot\" aria-label=\"Kilometer per Cubic Foot Fuel Efficiency Unit Description\">\n    <h3>Kilometer per Cubic Foot</h3>\n    \n    <p>Kilometer per cubic foot is a unit of fuel efficiency that measures the distance traveled in kilometers on one cubic foot of fuel. It provides a metric measurement for fuel efficiency at a volumetric scale.</p>\n \n    <p>Conversion: <strong>1 Kilometer per Cubic Foot (km/ft³) = 0.0283168 Meter per Liter (m/L)</strong></p>\n \n    <p>Kilometers per cubic foot is a metric unit for fuel efficiency calculations, primarily for volumetric fuel measurements.</p>\n</section>",
    "mile-per-cubic-meter": "<section id=\"mile-per-cubic-meter\" aria-label=\"Mile per Cubic Meter Fuel Efficiency Unit Description\">\n    <h3>Mile per Cubic Meter</h3>\n    \n    <p>Mile per cubic meter is a unit of fuel efficiency representing the distance traveled in miles on one cubic meter of fuel. It's used for measuring fuel efficiency at a volumetric level in the metric system.</p>\n \n    <p>Conversion: <strong>1 Mile per Cubic Meter (mi/m³) = 6.21e-7 Meter per Liter (m/L)</strong></p>\n \n    <p>Miles per cubic meter is a metric unit for fuel efficiency calculations, focusing on fuel volume in the metric system.</p>\n</section>",
    "mile-per-cubic-inch": "<section id=\"mile-per-cubic-inch\" aria-label=\"Mile per Cubic Inch Fuel Efficiency Unit Description\">\n    <h3>Mile per Cubic Inch</h3>\n    \n    <p>Mile per cubic inch is a unit of fuel efficiency that represents the distance traveled in miles on one cubic inch of fuel. It's a specialized unit used for precise measurements of fuel efficiency at very small volumes.</p>\n \n    <p>Conversion: <strong>1 Mile per Cubic Inch (mi/in³) = 2.54e-8 Meter per Liter (m/L)</strong></p>\n \n    <p>Miles per cubic inch is a tiny unit for fuel efficiency calculations, primarily in specialized fields.</p>\n</section>",
    "meter-per-cubic-inch": "<section id=\"meter-per-cubic-inch\" aria-label=\"Meter per Cubic Inch Fuel Efficiency Unit Description\">\n    <h3>Meter per Cubic Inch</h3>\n    \n    <p>Meter per cubic inch is a unit of fuel efficiency that measures the distance traveled in meters on one cubic inch of fuel. It's used for precise measurements of fuel efficiency at small volumes in the metric system.</p>\n \n    <p>Conversion: <strong>1 Meter per Cubic Inch (m/in³) = 0.0000610236 Meter per Liter (m/L)</strong></p>\n \n    <p>Meters per cubic inch is a metric unit for fuel efficiency calculations, especially in technical applications requiring small volume measurements.</p>\n</section>",
    "mile-per-cubic-centimeter": "<section id=\"mile-per-cubic-centimeter\" aria-label=\"Mile per Cubic Centimeter Fuel Efficiency Unit Description\">\n    <h3>Mile per Cubic Centimeter</h3>\n    \n    <p>Mile per cubic centimeter is a unit of fuel efficiency that represents the distance traveled in miles on one cubic centimeter of fuel. It's a very specialized unit used for extremely precise measurements of fuel efficiency at minuscule volumes.</p>\n \n    <p>Conversion: <strong>1 Mile per Cubic Centimeter (mi/cm³) = 6.21e-7 Meter per Liter (m/L)</strong></p>\n \n    <p>Miles per cubic centimeter is an exceptionally small unit for fuel efficiency calculations, typically employed in highly specialized applications requiring ultra-precise volume measurements.</p>\n</section>"
}

  getDescription(unitName: string) {
    return this.conversionDescriptions[unitName];
  }


}