import { Injectable } from '@angular/core';

@Injectable()
export class UnitsInfoService {
  private conversionDescriptions: any = {
    "binary": `<section id="binary" aria-label="Binary Description">          <h3>Binary</h3>                <p>Binary is a numerical base machine that employs simplest two digits, 0 and 1, to represent numbers. This base-2 system is the muse of virtual computing, serving because the language of computer systems and electronic gadgets. In binary, each digit represents a strength of two, making it a essential machine for encoding and processing records in computing.</p>                <p>Conversion: <strong>1 Binary (base 2) = 1 Decimal (base 10)</strong></p>                <p>Binary plays a pivotal role in pc technological know-how, enabling the representation of information, commands, and garage at the center of modern-day technology.</p>      </section>`,
    "octal": `<section id="octal" aria-label="Octal Description">          <h3>Octal</h3>                <p>Octal is a numerical base machine that makes use of 8 digits, 0 to 7, for numerical representation. Although much less not unusual than binary and decimal, octal is important in various computing packages, mainly in Unix-like running structures. It gives a compact way to specific binary values, as each octal digit corresponds to 3 binary digits.</p>                <p>Conversion: <strong>1 Octal (base 8) = 1 Decimal (base 10)</strong></p>                <p>Octal's significance is in particular obvious in document permissions, in which it simplifies the management of access rights for documents and directories.</p>      </section>`,
    "decimal": `<section id="decimal" aria-label="Decimal Description">          <h3>Decimal</h3>                <p>Decimal, or base 10, is the numerical base gadget that is maximum acquainted to people worldwide. It employs ten digits: zero to 9, for representing numbers. Decimal is the same old for ordinary mathematics and arithmetic, making it a essential gadget for human information and conversation of numerical quantities.</p>                <p>Conversion: <strong>1 Decimal (base 10) = 1 Decimal (base 10)</strong></p>                <p>Decimal is the cornerstone of mathematics, finance, and fashionable numerical operations, forming the basis for calculations in various fields of observe and commerce.</p>      </section>`,
    "hexadecimal": `<section id="hexadecimal" aria-label="Hexadecimal Description">          <h3>Hexadecimal</h3>                <p>Hexadecimal, often called hex, is a numerical base machine that employs sixteen digits: zero to nine and A to F (or a to f). It is extensively used in pc programming and virtual systems design, as it offers a handy way to represent binary records in a greater compact and human-readable shape.</p>                <p>Conversion: <strong>1 Hexadecimal (base 16) = 1 Decimal (base 10)</strong></p>                <p>Hexadecimal is quintessential to low-degree programming, records encoding, and addressing in laptop systems, presenting a bridge between binary and human-readable codecs.</p>      </section>`
}

  getDescription(unitName: string) {
    return this.conversionDescriptions[unitName];
  }


}