import { Injectable } from '@angular/core';

@Injectable()
export class UnitsInfoService {
  private conversionDescriptions: any ={
    "meter-per-second": `<section id="meter-per-second-speed-unit" aria-label="Meter per Second (m/s) Speed Unit Description">        <h3>Meter per Second (m/s) Speed Unit</h3>                <p>The meter per second (m/s) is the bottom unit of speed inside the International System of Units (SI) and is generally used for measuring the speed of objects. It represents the sspeed traveled in one second.</p>             <p>Conversion: <strong>1 Meter per Second (m/s) = 0.277778 Kilometers per Hour (km/h) = 0.44704 Miles per Hour (mph) = zero.3048 Feet per Second (feet/s) = zero.514444 Knots (kt) = 343.2 Mach (Ma)</strong></p>             <p>Meters per second are the usual unit for speed dimension in most medical and everyday contexts.</p>             <p>When using our speed converter, you could input values in meters per second to convert them to other velocity devices, facilitating speed-related calculations.</p>    </section>`,
    "kilometer-per-hour": `<section id="kilometer-per-hour-speed-unit" aria-label="Kilometer per Hour (km/h) Speed Unit Description">        <h3>Kilometer per Hour (km/h) Speed Unit</h3>                <p>The kilometer per hour (km/h) is a typically used speed unit in many nations for measuring the rate of vehicles and wind. It represents the sspeed of one kilometer traveled in one hour.</p>             <p>Conversion: <strong>1 Kilometer per Hour (km/h) = three.6 Meters per Second (m/s) = 0.621371 Miles per Hour (mph) = 0.911344 Knots (kt) = 61.2 Mach (Ma)</strong></p>             <p>Kilometers per hour are regularly used for velocity limits on roads and highways.</p>             <p>When the usage of our velocity converter, you could input values in kilometers per hour to transform them to other speed devices, making it handy for numerous speed-related calculations.</p>    </section>`,
    "mile-per-hour": `<section id="mile-per-hour-speed-unit" aria-label="Mile per Hour (mph) Speed Unit Description">        <h3>Mile per Hour (mph) Speed Unit</h3>                <p>The mile per hour (mph) is a not unusual speed unit on the whole used in the United States and a few other nations. It represents the distance of 1 mile traveled in a single hour.</p>             <p>Conversion: <strong>1 Mile per Hour (mph) = 1.60934 Kilometers per Hour (km/h) = zero.44704 Meters per Second (m/s) = 1.46667 Feet per Second (toes/s) = zero.868976 Knots (kt) = 761.1 Mach (Ma)</strong></p>             <p>Miles per hour are used for velocity limits on highways and in aviation for airspeed measurement.</p>             <p>When the usage of our velocity converter, you can input values in miles per hour to transform them to other velocity devices, facilitating velocity-related calculations.</p>    </section>`,
    "foot-per-second": `<section id="foot-per-second-speed-unit" aria-label="Foot per Second (ft/s) Speed Unit Description">        <h3>Foot per Second (ft/s) Speed Unit</h3>                <p>The foot per second (ft/s) is an imperial unit of velocity usually used inside the United States. It represents the distance of 1 foot traveled in a single second.</p>             <p>Conversion: <strong>1 Foot per Second (feet/s) = zero.3048 Meters per Second (m/s) = 1.09728 Kilometers per Hour (km/h) = zero.681818 Miles per Hour (mph) = 1.68781 Knots (kt) = a hundred and forty four Mach (Ma)</strong></p>             <p>Feet per second are utilized in diverse engineering and medical contexts inside the United States.</p>             <p>When using our speed converter, you may enter values in feet per second to convert them to different speed devices, aiding in velocity-associated calculations.</p>    </section>`,
    "knot": `<section id="knot-speed-unit" aria-label="Knot (kt) Speed Unit Description">        <h3>Knot (kt) Speed Unit</h3>                <p>The knot (kt) is a unit of speed commonly used in aviation and maritime contexts. It represents one nautical mile per hour, that's a wellknown for measuring velocity over water.</p>             <p>Conversion: <strong>1 Knot (kt) = 1.852 Kilometers per Hour (km/h) = 0.514444 Meters per Second (m/s) = 1.15078 Miles per Hour (mph) = 1.68781 Feet per Second (feet/s) = 6076.12 Mach (Ma)</strong></p>             <p>Knots are the standard unit for measuring the speed of plane and boats.</p>             <p>When the usage of our speed converter, you can input values in knots to convert them to other speed devices, aiding in speed-related calculations for aviation and maritime functions.</p>    </section>`,
    "mach": `<section id="mach-speed-unit" aria-label="Mach (Ma) Speed Unit Description">        <h3>Mach (Ma) Speed Unit</h3>                <p>The Mach (Ma) is a dimensionless unit that represents the ratio of an object's velocity to the rate of sound in a specific medium. It is generally used in aerodynamics and aviation.</p>             <p>Conversion: <strong>1 Mach (Ma) = 343.2 Meters per Second (m/s) = 1235.76 Kilometers per Hour (km/h) = 767.269 Miles per Hour (mph) = 1125.33 Feet per Second (ft/s) = 0.592483 Knots (kt)</strong></p>             <p>Mach numbers are used to explain how speedy an item is transferring as compared to the rate of sound in a particular medium, often air.</p>             <p>When using our speed converter, you can enter values in Mach numbers to convert them to different speed units, assisting in aerodynamic and aviation calculations.</p>    </section>`,
    "speed-of-light": `<section id="speed-of-light-speed-unit" aria-label="Speed of Light (c) Speed Unit Description">        <h3>Speed of Light (c) Speed Unit</h3>                <p>The speed of light (c) is the fastest velocity at which statistics or energy can tour in a vacuum. It performs a crucial role in the principle of relativity and the essential laws of physics.</p>             <p>Conversion: <strong>1 Speed of Light (c) = 299,792,458 Meters per Second (m/s) = 299,792.458 Kilometers per Second (km/s) = 186,282.397 Miles per Second (mi/s) = 299,792,458,000 Millimeters per Second (mm/s)</strong></p>             <p>The velocity of light is a fundamental steady in physics and is regularly used as a reference for comparing different speeds.</p>             <p>When the use of our velocity converter, you may input values in the speed of light to transform them to other speed units, despite the fact that that is commonly for theoretical or scientific purposes.</p>    </section>`,
    "kilometer-per-second": `<section id="kilometer-per-second-speed-unit" aria-label="Kilometer per Second Speed Unit Description">        <h3>Kilometer per Second Speed Unit</h3>                <p>The kilometer per second (km/s) is a velocity unit normally used in clinical and engineering contexts. It represents the distance of one kilometer traveled in one second.</p>             <p>Conversion: <strong>1 Kilometer per Second (km/s) = 1,000 Meters per Second (m/s) = zero.621371 Mile per Second (mi/s) = one million Millimeters per Second (mm/s)</strong></p>             <p>Kilometers per second are frequently utilized in physics and astronomy for describing high-speed phenomena.</p>             <p>When the usage of our velocity converter, you may input values in kilometers per second to convert them to other speed units, facilitating scientific and engineering calculations.</p>    </section>`,
    "mile-per-second": `<section id="mile-per-second-speed-unit" aria-label="Mile per Second Speed Unit Description">        <h3>Mile per Second Speed Unit</h3>                <p>The mile per second (mi/s) is a speed unit that represents the distance of one mile traveled in one second. It is every now and then used in clinical and engineering contexts.</p>             <p>Conversion: <strong>1 Mile per Second (mi/s) = 1.60934 Kilometers per Second (km/s) = 1,609.34 Meters per Second (m/s) = 1,609,340 Millimeters per Second (mm/s)</strong></p>             <p>Miles per second aren't as generally used as other velocity gadgets but can be encountered in sure technical applications.</p>             <p>When using our velocity converter, you can enter values in miles per second to transform them to other velocity gadgets for specialised calculations.</p>    </section>`,
    "yard-per-second": `<section id="yard-per-second-speed-unit" aria-label="Yard per Second Speed Unit Description">        <h3>Yard per Second Speed Unit</h3>                <p>The yard per second (yd/s) is a speed unit that represents the gap of one yard traveled in one second. It is much less common than different velocity devices however can be encountered in precise contexts.</p>             <p>Conversion: <strong>1 Yard per Second (yd/s) = zero.9144 Meters per Second (m/s) = zero.000568182 Mile per Second (mi/s) = 914.4 Millimeters per Second (mm/s)</strong></p>             <p>Yards per second aren't extensively used, however they can be useful for sure measurements that contain yards as a unit of distance.</p>             <p>When the use of our velocity converter, you can enter values in yards per second to convert them to different velocity gadgets for specialised calculations.</p>    </section>`,
    "inch-per-second": `<section id="inch-per-second-speed-unit" aria-label="Inch per Second Speed Unit Description">        <h3>Inch per Second Speed Unit</h3>                <p>The inch per second (in/s) is a speed unit that represents the distance of 1 inch traveled in one second. It is a distinctly small unit of velocity utilized in sure technical packages.</p>             <p>Conversion: <strong>1 Inch per Second (in/s) = zero.0254 Meters per Second (m/s) = zero.0000157833 Mile per Second (mi/s) = 25.Four Millimeters per Second (mm/s)</strong></p>             <p>Inches per second are usually used in specialized fields where precise measurements at small scales are required.</p>             <p>When using our speed converter, you can input values in inches per second to convert them to other velocity gadgets for specific technical calculations.</p>    </section>`,
    "light-year-per-year": `<section id="light-year-per-year-speed-unit" aria-label="Light-Year per Year Speed Unit Description">    <h3>Light-Year per Year Speed Unit</h3>        <p>The light-year per year is a unit used in astronomy to explain extraordinarily sizable distances. It represents the distance that light travels in one year in a vacuum. This unit is generally used to degree astronomical distances.</p>     <p>Conversion: <strong>1 Light-Year per Year = nine.461×10^15 Meters per Second (m/s)</strong></p>     <p>The light-year per year is an essential unit in astronomy for discussing the distances between celestial gadgets, which includes stars and galaxies.</p></section>`,
    "parsec-per-year": `<section id="parsec-per-year-speed-unit" aria-label="Parsec per Year Speed Unit Description">    <h3>Parsec per Year Speed Unit</h3>        <p>The parsec per year is every other astronomical unit for measuring fairly massive distances. It represents the sspeed at which an item would have a parallax attitude of one arcsecond when observed from Earth's orbit over the route of three hundred and sixty five days.</p>     <p>Conversion: <strong>1 Parsec per Year = three.086×10^sixteen Meters per Second (m/s)</strong></p>     <p>Parsecs are commonly utilized in astronomy to describe the distances between stars and galaxies.</p></section>`,
    "furlong-per-fortnight": `<section id="furlong-per-fortnight-speed-unit" aria-label="Furlong per Fortnight Speed Unit Description">    <h3>Furlong per Fortnight Speed Unit</h3>        <p>The furlong per fortnight is a unique unit of speed that represents the distance of one furlong (220 yards) traveled in one fortnight (14 days). It's a much less generally used unit of speed with unique historical or area of interest packages.</p>     <p>Conversion: <strong>1 Furlong per Fortnight = zero.00016630952381 Meters per Second (m/s)</strong></p>     <p>Furlongs per fortnight can also have historical relevance but aren't extensively used in current calculations.</p></section>`,
    "cable-per-minute": `<section id="cable-per-minute-speed-unit" aria-label="Cable per Minute Speed Unit Description">    <h3>Cable per Minute Speed Unit</h3>        <p>The cable per minute is a unit of speed frequently utilized in telecommunications and undersea cable industries. It represents the velocity at which facts or alerts journey alongside a cable.</p>     <p>Conversion: <strong>1 Cable per Minute = 185.2 Meters per Second (m/s)</strong></p>     <p>Cables per minute are relevant in telecommunications for measuring records transmission charges.</p></section>`,
    "cable-per-second": `<section id="cable-per-second-speed-unit" aria-label="Cable per Second Speed Unit Description">    <h3>Cable per Second Speed Unit</h3>        <p>The cable per second is a unit of speed regularly used in telecommunications and undersea cable industries. It represents the speed at which data or alerts tour alongside a cable.</p>     <p>Conversion: <strong>1 Cable per Second = 11112 Meters per Second (m/s)</strong></p>     <p>Cables per second are applicable in telecommunications for measuring statistics transmission quotes.</p></section>`,
    "nautical-mile-per-day": `<section id="nautical-mile-per-day-speed-unit" aria-label="Nautical Mile per Day Speed Unit Description">    <h3>Nautical Mile per Day Speed Unit</h3>        <p>The nautical mile per day is a unit of speed utilized in navigation and marine contexts. It represents the distance of one nautical mile (approximately 1.15078 statute miles) traveled in one day.</p>     <p>Conversion: <strong>1 Nautical Mile per Day = 1.94384 Knots (kn)</strong></p>     <p>Nautical miles per day are commonly used in maritime navigation and velocity calculations.</p></section>`,
    "nautical-mile-per-hour": `<section id="nautical-mile-per-hour-speed-unit" aria-label="Nautical Mile per Hour Speed Unit Description">    <h3>Nautical Mile per Hour Speed Unit</h3>        <p>The nautical mile per hour is a unit of speed utilized in navigation and marine contexts. It represents the gap of one nautical mile (approximately 1.15078 statute miles) traveled in a single hour.</p>     <p>Conversion: <strong>1 Nautical Mile per Hour = zero.514444 Meters per Second (m/s) = 1.852 Kilometers per Hour (km/h)</strong></p>     <p>Nautical miles per hour are typically used in maritime navigation and speed calculations.</p></section>`,
    "light-minute-per-year": `<section id="light-minute-per-year-speed-unit" aria-label="Light-Minute per Year Speed Unit Description">    <h3>Light-Minute per Year Speed Unit</h3>        <p>The light-minute per year is a unit of speed utilized in astronomy and astrophysics to express the speed of light over extended durations. It represents the distance that light travels in a single minute in a vacuum over the direction of one year.</p>     <p>Conversion: <strong>1 Light-Minute per Year = 1.77827×10^19 Meters per Second (m/s)</strong></p>     <p>Light-minutes per year are relevant in astronomical calculations for measuring full-size distances inside the universe.</p></section>`,
    "light-hour-per-year": `<section id="light-hour-per-year-speed-unit" aria-label="Light-Hour per Year Speed Unit Description">    <h3>Light-Hour per Year Speed Unit</h3>        <p>The light-hour per year is any other astronomical unit of speed used to explain the velocity of light over prolonged periods. It represents the distance that light travels in a single hour in a vacuum over the path of 365 days.</p>     <p>Conversion: <strong>1 Light-Hour per Year = 1.06696×10^21 Meters per Second (m/s)</strong></p>     <p>Light-hours per year are applicable in astronomical calculations for measuring substantial distances inside the universe.</p></section>`
  }

  getDescription(unitName: string) {
    return this.conversionDescriptions[unitName];
  }


}