import { Injectable } from '@angular/core';

@Injectable()
export class UnitsInfoService {
  private conversionDescriptions: any ={
    "meter-per-second": "<section id=\"meter-per-second-speed-unit\" aria-label=\"Meter per Second (m/s) Speed Unit Description\">\n        <h3>Meter per Second (m/s) Speed Unit</h3>\n        \n        <p>The meter per second (m/s) is the base unit of speed in the International System of Units (SI) and is commonly used for measuring the speed of objects. It represents the distance traveled in one second.</p>\n     \n        <p>Conversion: <strong>1 Meter per Second (m/s) = 0.277778 Kilometers per Hour (km/h) = 0.44704 Miles per Hour (mph) = 0.3048 Feet per Second (ft/s) = 0.514444 Knots (kt) = 343.2 Mach (Ma)</strong></p>\n     \n        <p>Meters per second are the standard unit for speed measurement in most scientific and everyday contexts.</p>\n     \n        <p>When using our speed converter, you can input values in meters per second to convert them to other speed units, facilitating speed-related calculations.</p>\n    </section>",
    "kilometer-per-hour": "<section id=\"kilometer-per-hour-speed-unit\" aria-label=\"Kilometer per Hour (km/h) Speed Unit Description\">\n        <h3>Kilometer per Hour (km/h) Speed Unit</h3>\n        \n        <p>The kilometer per hour (km/h) is a commonly used speed unit in many countries for measuring the speed of vehicles and wind. It represents the distance of one kilometer traveled in one hour.</p>\n     \n        <p>Conversion: <strong>1 Kilometer per Hour (km/h) = 3.6 Meters per Second (m/s) = 0.621371 Miles per Hour (mph) = 0.911344 Knots (kt) = 61.2 Mach (Ma)</strong></p>\n     \n        <p>Kilometers per hour are frequently used for speed limits on roads and highways.</p>\n     \n        <p>When using our speed converter, you can input values in kilometers per hour to convert them to other speed units, making it convenient for various speed-related calculations.</p>\n    </section>",
    "mile-per-hour": "<section id=\"mile-per-hour-speed-unit\" aria-label=\"Mile per Hour (mph) Speed Unit Description\">\n        <h3>Mile per Hour (mph) Speed Unit</h3>\n        \n        <p>The mile per hour (mph) is a common speed unit primarily used in the United States and a few other countries. It represents the distance of one mile traveled in one hour.</p>\n     \n        <p>Conversion: <strong>1 Mile per Hour (mph) = 1.60934 Kilometers per Hour (km/h) = 0.44704 Meters per Second (m/s) = 1.46667 Feet per Second (ft/s) = 0.868976 Knots (kt) = 761.1 Mach (Ma)</strong></p>\n     \n        <p>Miles per hour are used for speed limits on highways and in aviation for airspeed measurement.</p>\n     \n        <p>When using our speed converter, you can input values in miles per hour to convert them to other speed units, facilitating speed-related calculations.</p>\n    </section>",
    "foot-per-second": "<section id=\"foot-per-second-speed-unit\" aria-label=\"Foot per Second (ft/s) Speed Unit Description\">\n        <h3>Foot per Second (ft/s) Speed Unit</h3>\n        \n        <p>The foot per second (ft/s) is an imperial unit of speed commonly used in the United States. It represents the distance of one foot traveled in one second.</p>\n     \n        <p>Conversion: <strong>1 Foot per Second (ft/s) = 0.3048 Meters per Second (m/s) = 1.09728 Kilometers per Hour (km/h) = 0.681818 Miles per Hour (mph) = 1.68781 Knots (kt) = 144 Mach (Ma)</strong></p>\n     \n        <p>Feet per second are used in various engineering and scientific contexts in the United States.</p>\n     \n        <p>When using our speed converter, you can input values in feet per second to convert them to other speed units, aiding in speed-related calculations.</p>\n    </section>",
    "knot": "<section id=\"knot-speed-unit\" aria-label=\"Knot (kt) Speed Unit Description\">\n        <h3>Knot (kt) Speed Unit</h3>\n        \n        <p>The knot (kt) is a unit of speed commonly used in aviation and maritime contexts. It represents one nautical mile per hour, which is a standard for measuring speed over water.</p>\n     \n        <p>Conversion: <strong>1 Knot (kt) = 1.852 Kilometers per Hour (km/h) = 0.514444 Meters per Second (m/s) = 1.15078 Miles per Hour (mph) = 1.68781 Feet per Second (ft/s) = 6076.12 Mach (Ma)</strong></p>\n     \n        <p>Knots are the standard unit for measuring the speed of aircraft and boats.</p>\n     \n        <p>When using our speed converter, you can input values in knots to convert them to other speed units, aiding in speed-related calculations for aviation and maritime purposes.</p>\n    </section>",
    "mach": "<section id=\"mach-speed-unit\" aria-label=\"Mach (Ma) Speed Unit Description\">\n        <h3>Mach (Ma) Speed Unit</h3>\n        \n        <p>The Mach (Ma) is a dimensionless unit that represents the ratio of an object's speed to the speed of sound in a specific medium. It is commonly used in aerodynamics and aviation.</p>\n     \n        <p>Conversion: <strong>1 Mach (Ma) = 343.2 Meters per Second (m/s) = 1235.76 Kilometers per Hour (km/h) = 767.269 Miles per Hour (mph) = 1125.33 Feet per Second (ft/s) = 0.592483 Knots (kt)</strong></p>\n     \n        <p>Mach numbers are used to describe how fast an object is moving compared to the speed of sound in a particular medium, often air.</p>\n     \n        <p>When using our speed converter, you can input values in Mach numbers to convert them to other speed units, aiding in aerodynamic and aviation calculations.</p>\n    </section>",
    "speed-of-light": "<section id=\"speed-of-light-speed-unit\" aria-label=\"Speed of Light (c) Speed Unit Description\">\n        <h3>Speed of Light (c) Speed Unit</h3>\n        \n        <p>The speed of light (c) is the fastest speed at which information or energy can travel in a vacuum. It plays a crucial role in the theory of relativity and the fundamental laws of physics.</p>\n     \n        <p>Conversion: <strong>1 Speed of Light (c) = 299,792,458 Meters per Second (m/s) = 299,792.458 Kilometers per Second (km/s) = 186,282.397 Miles per Second (mi/s) = 299,792,458,000 Millimeters per Second (mm/s)</strong></p>\n     \n        <p>The speed of light is a fundamental constant in physics and is often used as a reference for comparing other speeds.</p>\n     \n        <p>When using our speed converter, you can input values in the speed of light to convert them to other speed units, although this is usually for theoretical or scientific purposes.</p>\n    </section>",
    "kilometer-per-second": "<section id=\"kilometer-per-second-speed-unit\" aria-label=\"Kilometer per Second Speed Unit Description\">\n        <h3>Kilometer per Second Speed Unit</h3>\n        \n        <p>The kilometer per second (km/s) is a speed unit commonly used in scientific and engineering contexts. It represents the distance of one kilometer traveled in one second.</p>\n     \n        <p>Conversion: <strong>1 Kilometer per Second (km/s) = 1,000 Meters per Second (m/s) = 0.621371 Mile per Second (mi/s) = 1,000,000 Millimeters per Second (mm/s)</strong></p>\n     \n        <p>Kilometers per second are frequently used in physics and astronomy for describing high-speed phenomena.</p>\n     \n        <p>When using our speed converter, you can input values in kilometers per second to convert them to other speed units, facilitating scientific and engineering calculations.</p>\n    </section>",
    "mile-per-second": "<section id=\"mile-per-second-speed-unit\" aria-label=\"Mile per Second Speed Unit Description\">\n        <h3>Mile per Second Speed Unit</h3>\n        \n        <p>The mile per second (mi/s) is a speed unit that represents the distance of one mile traveled in one second. It is occasionally used in scientific and engineering contexts.</p>\n     \n        <p>Conversion: <strong>1 Mile per Second (mi/s) = 1.60934 Kilometers per Second (km/s) = 1,609.34 Meters per Second (m/s) = 1,609,340 Millimeters per Second (mm/s)</strong></p>\n     \n        <p>Miles per second are not as commonly used as other speed units but may be encountered in certain technical applications.</p>\n     \n        <p>When using our speed converter, you can input values in miles per second to convert them to other speed units for specialized calculations.</p>\n    </section>",
    "yard-per-second": "<section id=\"yard-per-second-speed-unit\" aria-label=\"Yard per Second Speed Unit Description\">\n        <h3>Yard per Second Speed Unit</h3>\n        \n        <p>The yard per second (yd/s) is a speed unit that represents the distance of one yard traveled in one second. It is less common than other speed units but may be encountered in specific contexts.</p>\n     \n        <p>Conversion: <strong>1 Yard per Second (yd/s) = 0.9144 Meters per Second (m/s) = 0.000568182 Mile per Second (mi/s) = 914.4 Millimeters per Second (mm/s)</strong></p>\n     \n        <p>Yards per second are not widely used, but they can be useful for certain measurements that involve yards as a unit of distance.</p>\n     \n        <p>When using our speed converter, you can input values in yards per second to convert them to other speed units for specialized calculations.</p>\n    </section>",
    "inch-per-second": "<section id=\"inch-per-second-speed-unit\" aria-label=\"Inch per Second Speed Unit Description\">\n        <h3>Inch per Second Speed Unit</h3>\n        \n        <p>The inch per second (in/s) is a speed unit that represents the distance of one inch traveled in one second. It is a relatively small unit of speed used in certain technical applications.</p>\n     \n        <p>Conversion: <strong>1 Inch per Second (in/s) = 0.0254 Meters per Second (m/s) = 0.0000157833 Mile per Second (mi/s) = 25.4 Millimeters per Second (mm/s)</strong></p>\n     \n        <p>Inches per second are typically used in specialized fields where precise measurements at small scales are required.</p>\n     \n        <p>When using our speed converter, you can input values in inches per second to convert them to other speed units for specific technical calculations.</p>\n    </section>",
    "light-year-per-year": "<section id=\"light-year-per-year-speed-unit\" aria-label=\"Light-Year per Year Speed Unit Description\">\n    <h3>Light-Year per Year Speed Unit</h3>\n    \n    <p>The light-year per year is a unit used in astronomy to describe extremely vast distances. It represents the distance that light travels in one year in a vacuum. This unit is typically used to measure astronomical distances.</p>\n \n    <p>Conversion: <strong>1 Light-Year per Year = 9.461×10^15 Meters per Second (m/s)</strong></p>\n \n    <p>The light-year per year is an essential unit in astronomy for discussing the distances between celestial objects, such as stars and galaxies.</p>\n</section>",
    "parsec-per-year": "<section id=\"parsec-per-year-speed-unit\" aria-label=\"Parsec per Year Speed Unit Description\">\n    <h3>Parsec per Year Speed Unit</h3>\n    \n    <p>The parsec per year is another astronomical unit for measuring incredibly large distances. It represents the distance at which an object would have a parallax angle of one arcsecond when observed from Earth's orbit over the course of one year.</p>\n \n    <p>Conversion: <strong>1 Parsec per Year = 3.086×10^16 Meters per Second (m/s)</strong></p>\n \n    <p>Parsecs are commonly used in astronomy to describe the distances between stars and galaxies.</p>\n</section>",
    "furlong-per-fortnight": "<section id=\"furlong-per-fortnight-speed-unit\" aria-label=\"Furlong per Fortnight Speed Unit Description\">\n    <h3>Furlong per Fortnight Speed Unit</h3>\n    \n    <p>The furlong per fortnight is a unique unit of speed that represents the distance of one furlong (220 yards) traveled in one fortnight (14 days). It's a less commonly used unit of speed with specific historical or niche applications.</p>\n \n    <p>Conversion: <strong>1 Furlong per Fortnight = 0.00016630952381 Meters per Second (m/s)</strong></p>\n \n    <p>Furlongs per fortnight may have historical relevance but are not widely used in modern calculations.</p>\n</section>",
    "cable-per-minute": "<section id=\"cable-per-minute-speed-unit\" aria-label=\"Cable per Minute Speed Unit Description\">\n    <h3>Cable per Minute Speed Unit</h3>\n    \n    <p>The cable per minute is a unit of speed often used in telecommunications and undersea cable industries. It represents the speed at which data or signals travel along a cable.</p>\n \n    <p>Conversion: <strong>1 Cable per Minute = 185.2 Meters per Second (m/s)</strong></p>\n \n    <p>Cables per minute are relevant in telecommunications for measuring data transmission rates.</p>\n</section>",
    "cable-per-second": "<section id=\"cable-per-second-speed-unit\" aria-label=\"Cable per Second Speed Unit Description\">\n    <h3>Cable per Second Speed Unit</h3>\n    \n    <p>The cable per second is a unit of speed often used in telecommunications and undersea cable industries. It represents the speed at which data or signals travel along a cable.</p>\n \n    <p>Conversion: <strong>1 Cable per Second = 11112 Meters per Second (m/s)</strong></p>\n \n    <p>Cables per second are relevant in telecommunications for measuring data transmission rates.</p>\n</section>",
    "nautical-mile-per-day": "<section id=\"nautical-mile-per-day-speed-unit\" aria-label=\"Nautical Mile per Day Speed Unit Description\">\n    <h3>Nautical Mile per Day Speed Unit</h3>\n    \n    <p>The nautical mile per day is a unit of speed used in navigation and marine contexts. It represents the distance of one nautical mile (approximately 1.15078 statute miles) traveled in one day.</p>\n \n    <p>Conversion: <strong>1 Nautical Mile per Day = 1.94384 Knots (kn)</strong></p>\n \n    <p>Nautical miles per day are commonly used in maritime navigation and speed calculations.</p>\n</section>",
    "nautical-mile-per-hour": "<section id=\"nautical-mile-per-hour-speed-unit\" aria-label=\"Nautical Mile per Hour Speed Unit Description\">\n    <h3>Nautical Mile per Hour Speed Unit</h3>\n    \n    <p>The nautical mile per hour is a unit of speed used in navigation and marine contexts. It represents the distance of one nautical mile (approximately 1.15078 statute miles) traveled in one hour.</p>\n \n    <p>Conversion: <strong>1 Nautical Mile per Hour = 0.514444 Meters per Second (m/s) = 1.852 Kilometers per Hour (km/h)</strong></p>\n \n    <p>Nautical miles per hour are commonly used in maritime navigation and speed calculations.</p>\n</section>",
    "light-minute-per-year": "<section id=\"light-minute-per-year-speed-unit\" aria-label=\"Light-Minute per Year Speed Unit Description\">\n    <h3>Light-Minute per Year Speed Unit</h3>\n    \n    <p>The light-minute per year is a unit of speed used in astronomy and astrophysics to express the speed of light over extended periods. It represents the distance that light travels in one minute in a vacuum over the course of one year.</p>\n \n    <p>Conversion: <strong>1 Light-Minute per Year = 1.77827×10^19 Meters per Second (m/s)</strong></p>\n \n    <p>Light-minutes per year are relevant in astronomical calculations for measuring vast distances in the universe.</p>\n</section>",
    "light-hour-per-year": "<section id=\"light-hour-per-year-speed-unit\" aria-label=\"Light-Hour per Year Speed Unit Description\">\n    <h3>Light-Hour per Year Speed Unit</h3>\n    \n    <p>The light-hour per year is another astronomical unit of speed used to describe the speed of light over extended periods. It represents the distance that light travels in one hour in a vacuum over the course of one year.</p>\n \n    <p>Conversion: <strong>1 Light-Hour per Year = 1.06696×10^21 Meters per Second (m/s)</strong></p>\n \n    <p>Light-hours per year are relevant in astronomical calculations for measuring vast distances in the universe.</p>\n</section>"
}

  getDescription(unitName: string) {
    return this.conversionDescriptions[unitName];
  }


}