import { Injectable } from '@angular/core';

@Injectable()
export class UnitsInfoService {
  private conversionDescriptions: any = {
    "degree": `<section id="degree-angular-unit" aria-label="Degree (°) Angular Unit Description">     <h3>Degree (°) Angular Unit</h3>          <p>The diploma (°) is a unit of angular measurement generally utilized in geometry, geography, and various medical disciplines. One degree is defined as 1/360th of a complete circle, and it's miles subdivided into mins and seconds for extra specific measurements.</p>       <p>Conversion: <strong>1 Degree (°) = 57.2958 Radians (rad) = 60 Arc-Minutes (') = 3600 Arc-Seconds ('')</strong></p>       <p>Degrees are widely used for measuring angles, instructions, and geographic coordinates.</p> </section>`,
    "radian": `<section id="radian-angular-unit" aria-label="Radian (rad) Angular Unit Description">     <h3>Radian (rad) Angular Unit</h3>          <p>The radian (rad) is a unit of angular dimension used in arithmetic, physics, and engineering. It represents the angle subtended at the center of a circle by using an arc with a length equal to the circle's radius. Radians are regularly desired in trigonometric and calculus calculations.</p>       <p>Conversion: <strong>1 Radian (rad) = zero.0166667 Degrees (°) = 60 Arc-Minutes (') = 3600 Arc-Seconds ('')</strong></p>       <p>Radians are the same old unit for angular dimension in lots of medical and mathematical contexts.</p> </section>`,
    "arc-minute": `<section id="arc-minute-angular-unit" aria-label="Arc-Minute (') Angular Unit Description">     <h3>Arc-Minute (') Angular Unit</h3>          <p>The arc-minute (') is a unit of angular measurement used for even extra specific angle measurements. It is equal to 1/sixtieth of a diploma or 1/21,600th of a whole circle.</p>       <p>Conversion: <strong>1 Arc-Minute (') = zero.000277778 Degrees (°) = zero.0166667 Radians (rad) = 60 Arc-Seconds ('')</strong></p>       <p>Arc-mins are regularly used in astronomy, navigation, and various technical fields.</p> </section>`,
    "arc-second": `<section id="arc-second-angular-unit" aria-label="Arc-Second ('') Angular Unit Description">     <h3>Arc-Second ('') Angular Unit</h3>          <p>The arc-second ('') is an even smaller unit of angular dimension, normally utilized in astronomy and geodesy. It is identical to at least one/60th of an arc-minute or 1/1,296,000th of a diploma.</p>       <p>Conversion: <strong>1 Arc-Second ('') = zero.000277778 Degrees (°) = zero.0000154321 Radians (rad) = 1/60 Arc-Minute (')</strong></p>       <p>Arc-seconds are critical for extremely specific angle measurements.</p> </section>`,
    "gradian": `<section id="gradian-angular-unit" aria-label="Gradian Angular Unit Description">     <h3>Gradian Angular Unit</h3>          <p>The gradian is an angular unit utilized in a few international locations and technical packages, specifically in land surveying and geodesy. One gradian is same to 1/four-hundredth of a circle.</p>       <p>Conversion: <strong>1 Gradian = 1.11111 Degrees (°) = 0.01570796 Radians (rad) = a hundred Arc-Gradians (gon)</strong></p>       <p>Gradians are often utilized in certain engineering and surveying contexts wherein angles are measured in grades or gons.</p> </section>`,
    "sextant": `<section id="sextant-angular-unit" aria-label="Sextant Angular Unit Description">     <h3>Sextant Angular Unit</h3>          <p>The sextant is an angular unit that represents one-sixtieth (1/60) of a complete circle or revolution. It is usually used in navigation, in particular for measuring the altitude of celestial items above the horizon.</p>       <p>Conversion: <strong>1 Sextant = 60 Degrees (°) = 1/6 Quadrant = 1/360 Revolution = 1/360 Circle</strong></p>       <p>Sextants are essential gear for celestial navigation at sea and in other applications wherein precise attitude measurements are required.</p> </section>`,
    "quadrant": `<section id="quadrant-angular-unit" aria-label="Quadrant Angular Unit Description">     <h3>Quadrant Angular Unit</h3>          <p>The quadrant is an angular unit that represents one-fourth (1/four) of a complete circle or revolution. It is usually utilized in geometry and engineering for attitude measurement and calculation.</p>       <p>Conversion: <strong>1 Quadrant = ninety Degrees (°) = 15 Minutes (') = 1/4 Revolution = 1/4 Circle</strong></p>       <p>Quadrants are used in numerous mathematical and technical contexts for measuring and calculating angles.</p> </section>`,
    "revolution": `<section id="revolution-angular-unit" aria-label="Revolution Angular Unit Description">     <h3>Revolution Angular Unit</h3>          <p>The revolution is an angular unit that represents a complete circle, which is equivalent to 360 stages. It is a fundamental unit utilized in mathematics, physics, and engineering for measuring angles and rotations.</p>       <p>Conversion: <strong>1 Revolution = 360 Degrees (°) = 60 Sextants = 4 Quadrants = 1 Circle</strong></p>       <p>Revolutions are the basis for measuring angles in lots of clinical and technical disciplines.</p> </section>`,
    "circle": `<section id="circle-angular-unit" aria-label="Circle Angular Unit Description">     <h3>Circle Angular Unit</h3>          <p>The circle is an angular unit that represents a entire rotation or cycle, equal to 360 ranges or one revolution. It is a fundamental concept in geometry and trigonometry.</p>       <p>Conversion: <strong>1 Circle = 360 Degrees (°) = 60 Sextants = four Quadrants = 1 Revolution</strong></p>       <p>Circles are used in numerous mathematical and scientific contexts for knowledge angles and rotations.</p> </section>`,
    "turn": `<section id="turn-angular-unit" aria-label="Turn Angular Unit Description">     <h3>Turn Angular Unit</h3>          <p>The turn is an angular unit that represents a complete revolution or rotation, equal to 360 degrees, one revolution, or one circle. It is utilized in various technical and mathematical applications for measuring rotations and angles.</p>       <p>Conversion: <strong>1 Turn = 360 Degrees (°) = 60 Sextants = four Quadrants = 1 Revolution = 1 Circle</strong></p>       <p>Turns are often employed in situations where a complete rotation or cycle needs to be quantified.</p> </section>`,
    "right-angle": `<section id="right-angle-angular-unit" aria-label="Right Angle Angular Unit Description">     <h3>Right Angle Angular Unit</h3>          <p>A right angle is an angular unit that represents 90 tiers. It is a essential idea in geometry, and it defines the perspective fashioned while two traces are perpendicular to each other.</p>       <p>Conversion: <strong>1 Right Angle = ninety Degrees (°)</strong></p>       <p>Right angles play a essential role in geometric and architectural designs where perpendicular lines and angles are critical.</p> </section>`,
    "gon": `<section id="gon-angular-unit" aria-label="Gon Angular Unit Description">     <h3>Gon Angular Unit</h3>          <p>The gon is an angular unit that represents approximately 1.11111 tiers. It is utilized in numerous technical and medical contexts, particularly in land surveying and engineering.</p>       <p>Conversion: <strong>1 Gon ≈ 1.11111 Degrees (°)</strong></p>       <p>Gons are hired for precise angle dimension in fields in which degree-based measurements are too coarse.</p> </section>`,
    "mil-nato": `<section id="mil-nato-angular-unit" aria-label="Mil-NATO Angular Unit Description">     <h3>Mil-NATO Angular Unit</h3>          <p>The mil-NATO (NATO mil) is an angular unit that represents approximately 0.05625 ranges. It is used in military and artillery calculations to degree angles for concentrated on and ballistics.</p>       <p>Conversion: <strong>1 Mil-NATO (NATO mil) ≈ 0.05625 Degrees (°)</strong></p>       <p>Mil-NATO is important in navy operations for unique focused on and aiming of guns.</p> </section>`,
    "mil-soviet": `<section id="mil-soviet-angular-unit" aria-label="Mil-Soviet Angular Unit Description">     <h3>Mil-Soviet Angular Unit</h3>          <p>The mil-Soviet (Soviet mil) is an angular unit that represents zero.06 stages. It is used in army and artillery calculations just like the mil-NATO for measuring angles related to focused on and ballistics.</p>       <p>Conversion: <strong>1 Mil-Soviet (Soviet mil) = 0.06 Degrees (°)</strong></p>       <p>Mil-Soviet is hired in army applications, in particular in countries that used the Soviet gadget for navy measurements.</p> </section>`,
    "mil-swedish": `<section id="mil-swedish-angular-unit" aria-label="Mil-Swedish Angular Unit Description">     <h3>Mil-Swedish Angular Unit</h3>          <p>The mil-Swedish (Swedish mil) is an angular unit that represents 0.0675 ranges. It is utilized in some army and engineering contexts, especially in Sweden and different regions where this unit is traditionally considerable.</p>       <p>Conversion: <strong>1 Mil-Swedish (Swedish mil) = 0.0675 Degrees (°)</strong></p>       <p>Mil-Swedish is hired in specialised programs in Sweden and regions motivated by Swedish measurement systems.</p> </section>`,
    "mil-russian": `<section id="mil-russian-angular-unit" aria-label="Mil-Russian Angular Unit Description">     <h3>Mil-Russian Angular Unit</h3>          <p>The mil-Russian (Russian mil) is an angular unit that represents approximately 0.0572958 degrees. It is used in navy and artillery calculations in Russia and some different nations.</p>       <p>Conversion: <strong>1 Mil-Russian (Russian mil) ≈ zero.0572958 Degrees (°)</strong></p>       <p>Mil-Russian is employed for specific attitude measurement in military applications, particularly in Russia.</p> </section>`,
    "mil-french": `<section id="mil-french-angular-unit" aria-label="Mil-French Angular Unit Description">     <h3>Mil-French Angular Unit</h3>          <p>The mil-French (French mil) is an angular unit that represents approximately 0.0628319 stages. It is used in navy and artillery calculations in France and a few other international locations.</p>       <p>Conversion: <strong>1 Mil-French (French mil) ≈ 0.0628319 Degrees (°)</strong></p>       <p>Mil-French is hired for unique attitude dimension in army applications, mainly in France.</p> </section>`,
    "mil-austria": `<section id="mil-austria-angular-unit" aria-label="Mil-Austria Angular Unit Description">     <h3>Mil-Austria Angular Unit</h3>          <p>The mil-Austria (Austrian mil) is an angular unit that represents about zero.0647997 stages. It is utilized in army and artillery calculations in Austria and a few other nations.</p>       <p>Conversion: <strong>1 Mil-Austria (Austrian mil) ≈ 0.0647997 Degrees (°)</strong></p>       <p>Mil-Austria is hired for unique perspective measurement in navy packages, in particular in Austria.</p> </section>`,
    "mil-german": `<section id="mil-german-angular-unit" aria-label="Mil-German Angular Unit Description">     <h3>Mil-German Angular Unit</h3>          <p>The mil-German (German mil) is an angular unit that represents approximately zero.0572958 tiers. It is utilized in army and artillery calculations in Germany and a few other countries.</p>       <p>Conversion: <strong>1 Mil-German (German mil) ≈ zero.0572958 Degrees (°)</strong></p>       <p>Mil-German is hired for specific attitude size in navy packages, especially in Germany.</p> </section>`,
    "mil-italian": `<section id="mil-italian-angular-unit" aria-label="Mil-Italian Angular Unit Description">     <h3>Mil-Italian Angular Unit</h3>          <p>The mil-Italian (Italian mil) is an angular unit that represents 0.0625 degrees. It is used in army and artillery calculations in Italy and a few other international locations.</p>       <p>Conversion: <strong>1 Mil-Italian (Italian mil) = zero.0625 Degrees (°)</strong></p>       <p>Mil-Italian is hired for unique angle dimension in navy applications, specially in Italy.</p> </section>`
   }

  getDescription(unitName: string) {
    return this.conversionDescriptions[unitName];
  }


}