import { Injectable } from '@angular/core';

@Injectable()
export class UnitsInfoService {
  private conversionDescriptions: any = {
    "degree": "<section id=\"degree-angular-unit\" aria-label=\"Degree (°) Angular Unit Description\">\n     <h3>Degree (°) Angular Unit</h3>\n     \n     <p>The degree (°) is a unit of angular measurement commonly used in geometry, geography, and various scientific disciplines. One degree is defined as 1/360th of a complete circle, and it is subdivided into minutes and seconds for more precise measurements.</p>\n  \n     <p>Conversion: <strong>1 Degree (°) = 57.2958 Radians (rad) = 60 Arc-Minutes (') = 3600 Arc-Seconds ('')</strong></p>\n  \n     <p>Degrees are widely used for measuring angles, directions, and geographic coordinates.</p>\n </section>",
    "radian": "<section id=\"radian-angular-unit\" aria-label=\"Radian (rad) Angular Unit Description\">\n     <h3>Radian (rad) Angular Unit</h3>\n     \n     <p>The radian (rad) is a unit of angular measurement used in mathematics, physics, and engineering. It represents the angle subtended at the center of a circle by an arc with a length equal to the circle's radius. Radians are often preferred in trigonometric and calculus calculations.</p>\n  \n     <p>Conversion: <strong>1 Radian (rad) = 0.0166667 Degrees (°) = 60 Arc-Minutes (') = 3600 Arc-Seconds ('')</strong></p>\n  \n     <p>Radians are the standard unit for angular measurement in many scientific and mathematical contexts.</p>\n </section>",
    "arc-minute": "<section id=\"arc-minute-angular-unit\" aria-label=\"Arc-Minute (') Angular Unit Description\">\n     <h3>Arc-Minute (') Angular Unit</h3>\n     \n     <p>The arc-minute (') is a unit of angular measurement used for even more precise angle measurements. It is equal to 1/60th of a degree or 1/21,600th of a complete circle.</p>\n  \n     <p>Conversion: <strong>1 Arc-Minute (') = 0.000277778 Degrees (°) = 0.0166667 Radians (rad) = 60 Arc-Seconds ('')</strong></p>\n  \n     <p>Arc-minutes are often used in astronomy, navigation, and various technical fields.</p>\n </section>",
    "arc-second": "<section id=\"arc-second-angular-unit\" aria-label=\"Arc-Second ('') Angular Unit Description\">\n     <h3>Arc-Second ('') Angular Unit</h3>\n     \n     <p>The arc-second ('') is an even smaller unit of angular measurement, commonly used in astronomy and geodesy. It is equal to 1/60th of an arc-minute or 1/1,296,000th of a degree.</p>\n  \n     <p>Conversion: <strong>1 Arc-Second ('') = 0.000277778 Degrees (°) = 0.0000154321 Radians (rad) = 1/60 Arc-Minute (')</strong></p>\n  \n     <p>Arc-seconds are crucial for extremely precise angle measurements.</p>\n </section>",
    "gradian": "<section id=\"gradian-angular-unit\" aria-label=\"Gradian Angular Unit Description\">\n     <h3>Gradian Angular Unit</h3>\n     \n     <p>The gradian is an angular unit used in some countries and technical applications, particularly in land surveying and geodesy. One gradian is equal to 1/400th of a circle.</p>\n  \n     <p>Conversion: <strong>1 Gradian = 1.11111 Degrees (°) = 0.01570796 Radians (rad) = 100 Arc-Gradians (gon)</strong></p>\n  \n     <p>Gradians are often used in certain engineering and surveying contexts where angles are measured in grades or gons.</p>\n </section>",
    "sextant": "<section id=\"sextant-angular-unit\" aria-label=\"Sextant Angular Unit Description\">\n     <h3>Sextant Angular Unit</h3>\n     \n     <p>The sextant is an angular unit that represents one-sixtieth (1/60) of a full circle or revolution. It is commonly used in navigation, particularly for measuring the altitude of celestial objects above the horizon.</p>\n  \n     <p>Conversion: <strong>1 Sextant = 60 Degrees (°) = 1/6 Quadrant = 1/360 Revolution = 1/360 Circle</strong></p>\n  \n     <p>Sextants are essential tools for celestial navigation at sea and in other applications where precise angle measurements are required.</p>\n </section>",
    "quadrant": "<section id=\"quadrant-angular-unit\" aria-label=\"Quadrant Angular Unit Description\">\n     <h3>Quadrant Angular Unit</h3>\n     \n     <p>The quadrant is an angular unit that represents one-fourth (1/4) of a full circle or revolution. It is commonly used in geometry and engineering for angle measurement and calculation.</p>\n  \n     <p>Conversion: <strong>1 Quadrant = 90 Degrees (°) = 15 Minutes (') = 1/4 Revolution = 1/4 Circle</strong></p>\n  \n     <p>Quadrants are used in various mathematical and technical contexts for measuring and calculating angles.</p>\n </section>",
    "revolution": "<section id=\"revolution-angular-unit\" aria-label=\"Revolution Angular Unit Description\">\n     <h3>Revolution Angular Unit</h3>\n     \n     <p>The revolution is an angular unit that represents a complete circle, which is equivalent to 360 degrees. It is a fundamental unit used in mathematics, physics, and engineering for measuring angles and rotations.</p>\n  \n     <p>Conversion: <strong>1 Revolution = 360 Degrees (°) = 60 Sextants = 4 Quadrants = 1 Circle</strong></p>\n  \n     <p>Revolutions are the basis for measuring angles in many scientific and technical disciplines.</p>\n </section>",
    "circle": "<section id=\"circle-angular-unit\" aria-label=\"Circle Angular Unit Description\">\n     <h3>Circle Angular Unit</h3>\n     \n     <p>The circle is an angular unit that represents a complete rotation or cycle, equivalent to 360 degrees or one revolution. It is a fundamental concept in geometry and trigonometry.</p>\n  \n     <p>Conversion: <strong>1 Circle = 360 Degrees (°) = 60 Sextants = 4 Quadrants = 1 Revolution</strong></p>\n  \n     <p>Circles are used in various mathematical and scientific contexts for understanding angles and rotations.</p>\n </section>",
    "turn": "<section id=\"turn-angular-unit\" aria-label=\"Turn Angular Unit Description\">\n     <h3>Turn Angular Unit</h3>\n     \n     <p>The turn is an angular unit that represents a complete revolution or rotation, equivalent to 360 degrees, one revolution, or one circle. It is used in various technical and mathematical applications for measuring rotations and angles.</p>\n  \n     <p>Conversion: <strong>1 Turn = 360 Degrees (°) = 60 Sextants = 4 Quadrants = 1 Revolution = 1 Circle</strong></p>\n  \n     <p>Turns are often employed in scenarios where a full rotation or cycle needs to be quantified.</p>\n </section>",
    "right-angle": "<section id=\"right-angle-angular-unit\" aria-label=\"Right Angle Angular Unit Description\">\n     <h3>Right Angle Angular Unit</h3>\n     \n     <p>A right angle is an angular unit that represents 90 degrees. It is a fundamental concept in geometry, and it defines the angle formed when two lines are perpendicular to each other.</p>\n  \n     <p>Conversion: <strong>1 Right Angle = 90 Degrees (°)</strong></p>\n  \n     <p>Right angles play a crucial role in geometric and architectural designs where perpendicular lines and angles are essential.</p>\n </section>",
    "gon": "<section id=\"gon-angular-unit\" aria-label=\"Gon Angular Unit Description\">\n     <h3>Gon Angular Unit</h3>\n     \n     <p>The gon is an angular unit that represents approximately 1.11111 degrees. It is used in various technical and scientific contexts, particularly in land surveying and engineering.</p>\n  \n     <p>Conversion: <strong>1 Gon ≈ 1.11111 Degrees (°)</strong></p>\n  \n     <p>Gons are employed for precise angle measurement in fields where degree-based measurements are too coarse.</p>\n </section>",
    "mil-nato": "<section id=\"mil-nato-angular-unit\" aria-label=\"Mil-NATO Angular Unit Description\">\n     <h3>Mil-NATO Angular Unit</h3>\n     \n     <p>The mil-NATO (NATO mil) is an angular unit that represents approximately 0.05625 degrees. It is used in military and artillery calculations to measure angles for targeting and ballistics.</p>\n  \n     <p>Conversion: <strong>1 Mil-NATO (NATO mil) ≈ 0.05625 Degrees (°)</strong></p>\n  \n     <p>Mil-NATO is crucial in military operations for precise targeting and aiming of weapons.</p>\n </section>",
    "mil-soviet": "<section id=\"mil-soviet-angular-unit\" aria-label=\"Mil-Soviet Angular Unit Description\">\n     <h3>Mil-Soviet Angular Unit</h3>\n     \n     <p>The mil-Soviet (Soviet mil) is an angular unit that represents 0.06 degrees. It is used in military and artillery calculations similar to the mil-NATO for measuring angles related to targeting and ballistics.</p>\n  \n     <p>Conversion: <strong>1 Mil-Soviet (Soviet mil) = 0.06 Degrees (°)</strong></p>\n  \n     <p>Mil-Soviet is employed in military applications, particularly in countries that used the Soviet system for military measurements.</p>\n </section>",
    "mil-swedish": "<section id=\"mil-swedish-angular-unit\" aria-label=\"Mil-Swedish Angular Unit Description\">\n     <h3>Mil-Swedish Angular Unit</h3>\n     \n     <p>The mil-Swedish (Swedish mil) is an angular unit that represents 0.0675 degrees. It is used in some military and engineering contexts, particularly in Sweden and other regions where this unit is historically significant.</p>\n  \n     <p>Conversion: <strong>1 Mil-Swedish (Swedish mil) = 0.0675 Degrees (°)</strong></p>\n  \n     <p>Mil-Swedish is employed in specialized applications in Sweden and areas influenced by Swedish measurement systems.</p>\n </section>",
    "mil-russian": "<section id=\"mil-russian-angular-unit\" aria-label=\"Mil-Russian Angular Unit Description\">\n     <h3>Mil-Russian Angular Unit</h3>\n     \n     <p>The mil-Russian (Russian mil) is an angular unit that represents approximately 0.0572958 degrees. It is used in military and artillery calculations in Russia and some other countries.</p>\n  \n     <p>Conversion: <strong>1 Mil-Russian (Russian mil) ≈ 0.0572958 Degrees (°)</strong></p>\n  \n     <p>Mil-Russian is employed for precise angle measurement in military applications, particularly in Russia.</p>\n </section>",
    "mil-french": "<section id=\"mil-french-angular-unit\" aria-label=\"Mil-French Angular Unit Description\">\n     <h3>Mil-French Angular Unit</h3>\n     \n     <p>The mil-French (French mil) is an angular unit that represents approximately 0.0628319 degrees. It is used in military and artillery calculations in France and some other countries.</p>\n  \n     <p>Conversion: <strong>1 Mil-French (French mil) ≈ 0.0628319 Degrees (°)</strong></p>\n  \n     <p>Mil-French is employed for precise angle measurement in military applications, particularly in France.</p>\n </section>",
    "mil-austria": "<section id=\"mil-austria-angular-unit\" aria-label=\"Mil-Austria Angular Unit Description\">\n     <h3>Mil-Austria Angular Unit</h3>\n     \n     <p>The mil-Austria (Austrian mil) is an angular unit that represents approximately 0.0647997 degrees. It is used in military and artillery calculations in Austria and some other countries.</p>\n  \n     <p>Conversion: <strong>1 Mil-Austria (Austrian mil) ≈ 0.0647997 Degrees (°)</strong></p>\n  \n     <p>Mil-Austria is employed for precise angle measurement in military applications, particularly in Austria.</p>\n </section>",
    "mil-german": "<section id=\"mil-german-angular-unit\" aria-label=\"Mil-German Angular Unit Description\">\n     <h3>Mil-German Angular Unit</h3>\n     \n     <p>The mil-German (German mil) is an angular unit that represents approximately 0.0572958 degrees. It is used in military and artillery calculations in Germany and some other countries.</p>\n  \n     <p>Conversion: <strong>1 Mil-German (German mil) ≈ 0.0572958 Degrees (°)</strong></p>\n  \n     <p>Mil-German is employed for precise angle measurement in military applications, particularly in Germany.</p>\n </section>",
    "mil-italian": "<section id=\"mil-italian-angular-unit\" aria-label=\"Mil-Italian Angular Unit Description\">\n     <h3>Mil-Italian Angular Unit</h3>\n     \n     <p>The mil-Italian (Italian mil) is an angular unit that represents 0.0625 degrees. It is used in military and artillery calculations in Italy and some other countries.</p>\n  \n     <p>Conversion: <strong>1 Mil-Italian (Italian mil) = 0.0625 Degrees (°)</strong></p>\n  \n     <p>Mil-Italian is employed for precise angle measurement in military applications, particularly in Italy.</p>\n </section>"
}

  getDescription(unitName: string) {
    return this.conversionDescriptions[unitName];
  }


}